[[carrier_id]]
mcc_mnc = "20404"

[carrier_id.mvno_data]
kind = "spn"
value = "JUMP"

[[settings.apns.apn]]
name = "Jump Roam"
value = "mobiledata"
type = []
authtype = 0

[settings.config]
default_vm_number = "+31654501233"
maxImageHeight = 1944
maxImageWidth = 2592
maxMessageSize = 1048576
show_4g_for_lte_data_icon = true
