[[carrier_id]]
mcc_mnc = "20601"

[carrier_id.mvno_data]
kind = "spn"
value = "IUSACELL"

[[carrier_id]]
mcc_mnc = "20601"

[carrier_id.mvno_data]
kind = "spn"
value = "UNEFON"

[[settings.apns.apn]]
name = "MMS"
value = "mms.iusacellgsm.mx"
type = ["mms"]
user = "mmsiusacellgsm"
password = "mmsiusacellgsm"
authtype = 0
mmsc = "http://mms.iusacell3g.com/"

[[settings.apns.apn]]
name = "MODEM"
value = "modem.iusacellgsm.mx"
type = ["dun"]
user = "iusacellgsm"
password = "iusacellgsm"
authtype = 0
user_editable = false

[[settings.apns.apn]]
name = "Internet"
value = "web.iusacellgsm.mx"
type = ["default"]
user = "iusacellgsm"
password = "iusacellgsm"
authtype = 0

[settings.config]
