[[carrier_id]]
mcc_mnc = "20801"

[carrier_id.mvno_data]
kind = "gid1"
value = "33"

[[settings.apns.apn]]
name = "Carrefour WAP"
value = "ofnew.fr"
type = ["default", "supl"]
proxy = "192.168.10.100"
port = "8080"
user = "orange"
password = "orange"
authtype = 1

[[settings.apns.apn]]
name = "Carrefour MMS"
value = "orange.acte"
type = ["mms"]
user = "orange"
password = "orange"
authtype = 1
mmsc = "http://mms.orange.fr"
mmsc_proxy = "192.168.10.200"
mmsc_proxy_port = "8080"

[settings.config]
maxImageHeight = 1944
maxImageWidth = 2592
maxMessageSize = 614400
prefer_2g = true
show_4g_for_lte_data_icon = true
