[[carrier_id]]
mcc_mnc = "20810"

[carrier_id.mvno_data]
kind = "gid1"
value = "44"

[[settings.apns.apn]]
name = "Darty Surf Mails"
value = "wap68"
type = ["dun"]
user_visible = false

[[settings.apns.apn]]
name = "Darty Surf&Mails"
value = "wap68"
type = ["default", "supl"]
proxy = "192.168.21.11"
port = "8080"

[[settings.apns.apn]]
name = "Darty MMS"
value = "mms68"
type = ["mms"]
mmsc = "http://mms68/"
mmsc_proxy = "10.143.156.11"
mmsc_proxy_port = "8080"

[settings.config]
maxImageHeight = 1944
maxImageWidth = 2592
maxMessageSize = 614400
prefer_2g = true
show_4g_for_lte_data_icon = true
