[[carrier_id]]
mcc_mnc = "20810"

[carrier_id.mvno_data]
kind = "spn"
value = "REGLOMOBILE"

[[settings.apns.apn]]
name = "WAP RegloMobile"
value = "wap66"
type = ["default", "supl", "dun", "fota"]
proxy = "192.168.21.9"
port = "8080"
authtype = 0
user_editable = false

[[settings.apns.apn]]
name = "MMS RegloMobile"
value = "mms66"
type = ["mms"]
authtype = 0
mmsc = "http://mms66"
mmsc_proxy = "10.143.156.9"
mmsc_proxy_port = "8080"

[settings.config]
maxImageHeight = 1944
maxImageWidth = 2592
maxMessageSize = 614400
prefer_2g = true
show_4g_for_lte_data_icon = true
