[[carrier_id]]
mcc_mnc = "20826"

[carrier_id.mvno_data]
kind = "gid1"
value = "4E"

[[settings.apns.apn]]
name = "NET26"
value = "net26"
type = ["default", "supl"]
authtype = 1
protocol = "ipv4v6"

[[settings.apns.apn]]
name = "MMS26"
value = "mms26"
type = ["mms"]
authtype = 1
mmsc = "http://mms26"
mmsc_proxy = "10.143.156.5"
mmsc_proxy_port = "8080"

[settings.config]
maxImageHeight = 1944
maxImageWidth = 2592
maxMessageSize = 614400
non_roaming_operator = ["20801", "20810"]
prefer_2g = true
show_4g_for_lte_data_icon = true
