[[carrier_id]]
mcc_mnc = "21406"

[carrier_id.mvno_data]
kind = "gid1"
value = "0008"

[[settings.apns.apn]]
name = "Euskaltel MMS"
value = "euskaltelmms.euskaltel.mobi"
type = ["mms"]
user = "MMS"
password = "EUSKALTEL"
authtype = 1
mmsc = "http://mms.euskaltel.mobi"
mmsc_proxy = "172.16.18.74"
mmsc_proxy_port = "8080"

[[settings.apns.apn]]
name = "Euskaltel Internet"
value = "internet.euskaltel.mobi"
type = ["default", "supl"]
user = "CLIENTE"
password = "EUSKALTEL"
authtype = 1

[settings.config]
non_roaming_operator = ["21401", "21402", "21403", "21404", "21405", "21407", "21408", "21409", "214010", "214011", "214012", "214013", "214014", "214015", "214016", "214017", "214018", "214019", "214020", "214021"]
show_4g_for_lte_data_icon = true
unloggable_numbers = ["900018018", "016", "021", "024", "028", "116000", "116111", "900202010"]
