[[carrier_id]]
mcc_mnc = "24005"

[carrier_id.mvno_data]
kind = "spn"
value = "TELIA"

[[settings.apns.apn]]
name = "Telia MMS"
value = "mms.telia.se"
type = ["mms"]
authtype = 0
mmsc = "http://mmss"
mmsc_proxy = "193.209.134.132"
mmsc_proxy_port = "80"

[[settings.apns.apn]]
name = "Telia"
value = "online.telia.se"
type = ["default", "supl"]
authtype = 0

[settings.config]
