[[carrier_id]]
mcc_mnc = "25002"

[settings]
version = 77000000001

[[settings.apns.apn]]
name = "Megafon Internet"
value = "internet"
type = ["default", "supl"]

[[settings.apns.apn]]
name = "Megafon MMS"
value = "mms"
type = ["mms"]
user = "mms"
password = "mms"
authtype = 1
mmsc = "http://mmsc:8002"
mmsc_proxy = "10.10.10.10"
mmsc_proxy_port = "8080"

[settings.config]
carrier_default_2g_protection_enabled = true
prefer_3g_visibility = false
carrier_default_wfc_ims_enabled = true
carrier_default_wfc_ims_mode = 1
carrier_default_wfc_ims_roaming_enabled = true
carrier_default_wfc_ims_roaming_mode = 1
carrier_volte_available = true
carrier_wfc_ims_available = true
hide_enhanced_4g_lte = true
editable_enhanced_4g_lte = false
show_4g_for_lte_data_icon = true
