[[carrier_id]]
mcc_mnc = "25704"

[[settings.apns.apn]]
name = "life:) Internet"
value = "internet.life.com.by"
type = ["default", "supl"]
authtype = 1

[[settings.apns.apn]]
name = "life:) MMS"
value = "mms.life.com.by"
type = ["mms"]
authtype = 1
mmsc = "http://mms.life.com.by/mmsc/"
mmsc_proxy = "10.10.10.20"
mmsc_proxy_port = "8080"

[settings.config]
