[[carrier_id]]
mcc_mnc = "310090"

[[settings.apns.apn]]
name = "Internet"
value = "isp"
type = ["default", "supl"]
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "MMS"
value = "mms"
type = ["mms"]
mmsc = "http://mms.edgemobile.net/mmsc"
mmsc_proxy = "12.108.12.13"
mmsc_proxy_port = "3128"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "Edge MMS Prepay"
value = "ppmms"
type = ["mms"]
mmsc = "http://mms.edgemobile.net/mmsc"
mmsc_proxy = "12.108.12.13"
mmsc_proxy_port = "3128"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[settings.config]
csp_enabled = true
maxImageHeight = 1944
maxImageWidth = 2592
maxMessageSize = 614400
