[[carrier_id]]
mcc_mnc = "310750"

[settings.config]
httpParams = "X-MDN: ##LINE1##"
maxImageHeight = 2432
maxImageWidth = 4320
maxMessageSize = 1228800
maxSubjectLength = 80
recipientLimit = 20
smsToMmsTextThreshold = 1
