[[carrier_id]]
mcc_mnc = "310920"

[settings.config]
httpParams = "X-MDN: ##LINE1##"
maxImageHeight = 2432
maxImageWidth = 4320
maxMessageSize = 1258291
maxSubjectLength = 80
recipientLimit = 20
smsToMmsTextThreshold = 1
