[[carrier_id]]
mcc_mnc = "311050"

[carrier_id.mvno_data]
kind = "spn"
value = "THUMBCELLULAR"

[[settings.apns.apn]]
name = "thumbcellular"
value = "CdmaNai"
type = ["mms"]
bearer_bitmask = "6"
mmsc = "http://mms.thumbcell.com/thumb/mms.php"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "Thumb IMS"
value = "VZWIMS"
type = ["ia", "ims"]
bearer_bitmask = "13"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "Thumb IMS"
value = "VZWIMS"
type = ["ia", "ims"]
bearer_bitmask = "14"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "Thumb FOTA"
value = "VZWADMIN"
type = ["fota"]
bearer_bitmask = "13"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "Thumb FOTA"
value = "VZWADMIN"
type = ["fota"]
bearer_bitmask = "14"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "Thumbcellular"
value = "VZWINTERNET"
type = ["default", "mms", "supl", "dun"]
bearer_bitmask = "13"
mmsc = "http://mms.thumbcell.com/thumb/mms.php"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_editable = false

[[settings.apns.apn]]
name = "Thumbcellular"
value = "VZWINTERNET"
type = ["default", "mms", "supl", "dun"]
bearer_bitmask = "14"
mmsc = "http://mms.thumbcell.com/thumb/mms.php"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_editable = false

[[settings.apns.apn]]
name = "Thumb IMS"
value = "IMS"
type = ["ia", "ims"]
bearer_bitmask = "13"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "Thumb IMS"
value = "IMS"
type = ["ia", "ims"]
bearer_bitmask = "14"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[settings.config]
