[[carrier_id]]
mcc_mnc = "311450"

[carrier_id.mvno_data]
kind = "spn"
value = "PTCI"

[[settings.apns.apn]]
name = "ptci"
value = "CdmaNai"
type = ["mms"]
bearer_bitmask = "6"
mmsc = "http://mmsc.ptci.net"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "Ptci IMS"
value = "VZWIMS"
type = ["ia", "ims"]
bearer_bitmask = "13"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "Ptci IMS"
value = "VZWIMS"
type = ["ia", "ims"]
bearer_bitmask = "14"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "Ptci FOTA"
value = "VZWADMIN"
type = ["fota"]
bearer_bitmask = "13"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "Ptci FOTA"
value = "VZWADMIN"
type = ["fota"]
bearer_bitmask = "14"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "Ptci"
value = "VZWINTERNET"
type = ["default", "mms", "supl", "dun"]
bearer_bitmask = "13"
mmsc = "http://mmsc.ptci.net"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_editable = false

[[settings.apns.apn]]
name = "Ptci"
value = "VZWINTERNET"
type = ["default", "mms", "supl", "dun"]
bearer_bitmask = "14"
mmsc = "http://mmsc.ptci.net"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_editable = false

[[settings.apns.apn]]
name = "Ptci IMS"
value = "IMS"
type = ["ia", "ims"]
bearer_bitmask = "13"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "Ptci IMS"
value = "IMS"
type = ["ia", "ims"]
bearer_bitmask = "14"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[settings.config]
