[[carrier_id]]
mcc_mnc = "311590"

[carrier_id.mvno_data]
kind = "spn"
value = "GSC"

[[settings.apns.apn]]
name = "gsc"
value = "CdmaNai"
type = ["mms"]
bearer_bitmask = "6"
mmsc = "http://mmsc1.gscdata.com"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "Gsc IMS"
value = "VZWIMS"
type = ["ia", "ims"]
bearer_bitmask = "13"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "Gsc IMS"
value = "VZWIMS"
type = ["ia", "ims"]
bearer_bitmask = "14"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "Gsc FOTA"
value = "VZWADMIN"
type = ["fota"]
bearer_bitmask = "13"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "Gsc FOTA"
value = "VZWADMIN"
type = ["fota"]
bearer_bitmask = "14"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "Gsc"
value = "VZWINTERNET"
type = ["default", "mms", "supl", "dun"]
bearer_bitmask = "13"
mmsc = "http://mmsc1.gscdata.com"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_editable = false

[[settings.apns.apn]]
name = "Gsc"
value = "VZWINTERNET"
type = ["default", "mms", "supl", "dun"]
bearer_bitmask = "14"
mmsc = "http://mmsc1.gscdata.com"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_editable = false

[[settings.apns.apn]]
name = "Gsc IMS"
value = "IMS"
type = ["ia", "ims"]
bearer_bitmask = "13"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "Gsc IMS"
value = "IMS"
type = ["ia", "ims"]
bearer_bitmask = "14"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[settings.config]
httpParams = "X-MDN: ##LINE1##"
maxImageHeight = 2432
maxImageWidth = 4320
maxMessageSize = 1048576
maxSubjectLength = 80
recipientLimit = 20
smsToMmsTextThreshold = 1
