[[carrier_id]]
mcc_mnc = "311610"

[carrier_id.mvno_data]
kind = "spn"
value = "SRTCOMM"

[[settings.apns.apn]]
name = "srtcomm"
value = "CdmaNai"
type = ["mms"]
bearer_bitmask = "6"
mmsc = "http://mms.iot1.com/srt/mms.php"
mmsc_proxy = "mms.iot1.com"
mmsc_proxy_port = "9201"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "Srtcomm IMS"
value = "VZWIMS"
type = ["ia", "ims"]
bearer_bitmask = "13"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "Srtcomm IMS"
value = "VZWIMS"
type = ["ia", "ims"]
bearer_bitmask = "14"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "Srtcomm FOTA"
value = "VZWADMIN"
type = ["fota"]
bearer_bitmask = "13"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "Srtcomm FOTA"
value = "VZWADMIN"
type = ["fota"]
bearer_bitmask = "14"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "Srtcomm"
value = "VZWINTERNET"
type = ["default", "mms", "supl", "dun"]
bearer_bitmask = "13"
mmsc = "http://mms.iot1.com/srt/mms.php"
mmsc_proxy = "mms.iot1.com"
mmsc_proxy_port = "9201"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_editable = false

[[settings.apns.apn]]
name = "Srtcomm"
value = "VZWINTERNET"
type = ["default", "mms", "supl", "dun"]
bearer_bitmask = "14"
mmsc = "http://mms.iot1.com/srt/mms.php"
mmsc_proxy = "mms.iot1.com"
mmsc_proxy_port = "9201"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_editable = false

[[settings.apns.apn]]
name = "Srtcomm IMS"
value = "IMS"
type = ["ia", "ims"]
bearer_bitmask = "13"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "Srtcomm IMS"
value = "IMS"
type = ["ia", "ims"]
bearer_bitmask = "14"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[settings.config]
