[[carrier_id]]
mcc_mnc = "36269"

[[settings.apns.apn]]
name = "Curacao:Digicel:Internet"
value = "web.digicelcuracao.com"
type = ["default"]
authtype = 1

[[settings.apns.apn]]
name = "Curacao:Digicel:Mms"
value = "wap"
type = ["mms"]
authtype = 1
mmsc = "http://mms.digicelgroup.com"
mmsc_proxy = "172.16.7.12"
mmsc_proxy_port = "9201"

[[settings.apns.apn]]
name = "Curacao:Digicel:Modem"
value = "wap"
type = ["dun"]
proxy = "172.16.7.12"
port = "8080"
authtype = 1
mmsc = "http://wapdigicel.com"
user_editable = false

[settings.config]
