[[carrier_id]]
mcc_mnc = "376350"

[[settings.apns.apn]]
name = "Turks And Caicos:Lime:Internet"
value = "internet"
type = ["default"]
authtype = 1

[[settings.apns.apn]]
name = "Turks And Caicos:Lime:Mms"
value = "multimedia"
type = ["mms"]
authtype = 1
mmsc = "http://mmsc"
mmsc_proxy = "10.20.5.34"
mmsc_proxy_port = "8799"

[[settings.apns.apn]]
name = "Turks And Caicos:Lime:Modem"
value = "internet"
type = ["dun"]
authtype = 1
mmsc = "http://www.time4lime.com/"
user_editable = false

[settings.config]
