[[carrier_id]]
mcc_mnc = "41677"

[[settings.apns.apn]]
name = "Orange MMS"
value = "mms.orange.jo"
type = ["mms"]
user = "mmc"
password = "mmc"
authtype = 1
mmsc = "http://172.16.1.96/servlets/mms"
mmsc_proxy = "172.16.1.2"
mmsc_proxy_port = "8080"

[[settings.apns.apn]]
name = "Orange Internet"
value = "net.orange.jo"
type = ["default", "supl"]
user = "net"
password = "net"
authtype = 1

[[settings.apns.apn]]
name = "Orange WAP"
value = "wap.orange.jo"
type = ["default", "supl"]
proxy = "172.16.1.2"
port = "8080"
user = "wap"
password = "wap"
authtype = 1

[settings.config]
