[[carrier_id]]
mcc_mnc = "44120"

[settings.config]
carrier_force_disable_etws_cmas_test = true
carrier_volte_available = true
gsm_dtmf_tone_delay = 300
ims_dtmf_tone_delay = 300
maxImageHeight = 1944
maxImageWidth = 2592
maxMessageSize = 307200
recipientLimit = -1
show_4g_for_lte_data_icon = true
volte_replacement_rat = 3
