[[carrier_id]]
mcc_mnc = "45208"

[[settings.apns.apn]]
name = "e-internet"
value = "e-internet"
type = ["default", "supl"]

[[settings.apns.apn]]
name = "e-wap"
value = "e-wap"
type = ["default", "supl"]
proxy = "10.18.2.183"
port = "8080"

[[settings.apns.apn]]
name = "e-mms"
value = "e-mms"
type = ["mms"]
mmsc = "http://10.18.2.172:38090"
mmsc_proxy = "10.18.2.183"
mmsc_proxy_port = "8080"

[settings.config]
