[[carrier_id]]
mcc_mnc = "51021"

[[settings.apns.apn]]
name = "Indosat-SNS"
value = "indosatgprs"
type = ["default", "supl"]
authtype = 1

[[settings.apns.apn]]
name = "Indosat GPRS"
value = "indosatgprs"
type = ["default", "supl"]
proxy = "10.19.19.19"
port = "8080"
user = "indosat"
password = "indosat"
authtype = 1

[[settings.apns.apn]]
name = "Indosat MMS"
value = "indosatmms"
type = ["mms"]
user = "indosat"
password = "indosat"
authtype = 1
mmsc = "http://mmsc.indosat.com"
mmsc_proxy = "10.19.19.19"
mmsc_proxy_port = "8080"

[settings.config]
non_roaming_operator = ["51001"]
