[[carrier_id]]
mcc_mnc = "52504"

[[settings.apns.apn]]
name = "Sunsurf Mobile"
value = "sunsurf"
type = ["default", "supl"]

[[settings.apns.apn]]
name = "M1 MMS(3G)"
value = "miworld"
type = ["mms"]
user = "65"
password = "user123"
authtype = 1
mmsc = "http://mmsgw:8002"
mmsc_proxy = "172.16.14.10"
mmsc_proxy_port = "8080"

[settings.config]
