[[carrier_id]]
mcc_mnc = "60303"

[[settings.apns.apn]]
name = "nedjmawap"
value = "nedjmawap"
type = ["default", "supl"]
proxy = "192.168.52.2"
port = "3128"
user = "wap"
password = "wap"
authtype = 1

[[settings.apns.apn]]
name = "Nedjma.dz"
value = "internet"
type = ["default", "supl"]
user = "nedjma"
password = "nedjma"

[[settings.apns.apn]]
name = "nedjmamms"
value = "nedjmamms"
type = ["mms"]
user = "mms"
password = "mms"
authtype = 1
mmsc = "http://10.10.111.1"
mmsc_proxy = "192.168.52.3"
mmsc_proxy_port = "3128"

[settings.config]
