[[carrier_id]]
mcc_mnc = "60302"

[[settings.apns.apn]]
name = "djezzy.internet"
value = "djezzy.internet"
type = ["default", "supl"]

[[settings.apns.apn]]
name = "djezzy.mms"
value = "djezzy.mms"
type = ["mms"]
user = "mms"
password = "mms"
mmsc = "http://172.24.97.152:6021/mmsc"
mmsc_proxy = "172.24.97.158"
mmsc_proxy_port = "8799"

[settings.config]
