[[carrier_id]]
mcc_mnc = "61202"

[[settings.apns.apn]]
name = "Moov Internet CI"
value = "moov"
type = ["default"]
proxy = "10.172.11.17"
port = "8080"
user = "web"
password = "web"

[settings.config]
