[[carrier_id]]
mcc_mnc = "62701"

[[settings.apns.apn]]
name = "Orange GQ"
value = "default"
type = ["default", "supl"]

[[settings.apns.apn]]
name = "Orange GQ MMS"
value = "orangemms"
type = ["mms"]
user = "mms"
password = "mms"
authtype = 0
mmsc = "http://192.168.17.34/servlets/mms"
mmsc_proxy = "192.168.17.2"
mmsc_proxy_port = "8080"

[settings.config]
