[[carrier_id]]
mcc_mnc = "63001"

[[settings.apns.apn]]
name = "Vodacom Internet CD"
value = "vodanet"
type = ["default"]

[[settings.apns.apn]]
name = "Vodacom MMS"
value = "vodalive"
type = ["mms"]
authtype = 0
mmsc = "http://172.24.97.1/mmsc"
mmsc_proxy = "172.24.97.1"
mmsc_proxy_port = "8080"

[settings.config]
