[[carrier_id]]
mcc_mnc = "65507"

[carrier_id.mvno_data]
kind = "imsi"
value = "6550713"

[[settings.apns.apn]]
name = "RBM Internet"
value = "mobile.redbullmobile.co.za"
type = ["default", "supl"]
proxy = "196.31.116.250"
port = "8080"

[[settings.apns.apn]]
name = "Redbull MMS"
value = "mms"
type = ["mms"]
mmsc = "http://mms.cmobile.co.za/"
mmsc_proxy = "196.31.116.250"
mmsc_proxy_port = "8080"

[settings.config]
