[[carrier_id]]
mcc_mnc = "71201"

[[settings.apns.apn]]
name = "KOLBI 3G"
value = "kolbi3g"
type = ["default", "supl"]

[[settings.apns.apn]]
name = "Costar Rica:Kolbi:Modem"
value = "kolbi"
type = ["dun"]
authtype = 1
mmsc = "http://mimundokolbi.ice.cr"
user_editable = false

[[settings.apns.apn]]
name = "Kolbi_Multimedia"
value = "kolbimundo"
type = ["mms"]
mmsc = "http://mmsice"
mmsc_proxy = "10.184.202.24"
mmsc_proxy_port = "8080"

[settings.config]
