[[carrier_id]]
mcc_mnc = "72407"

[[settings.apns.apn]]
name = "SCTL MMS"
value = "mms.sercomtel.com.br"
type = ["mms"]
user = "sercomtel"
password = "sercomtel"
mmsc = "http://mms.claro.com.br"
mmsc_proxy = "200.169.126.10"
mmsc_proxy_port = "8799"

[[settings.apns.apn]]
name = "SCTL GPRS"
value = "sercomtel.com.br"
type = ["default", "supl"]
user = "sercomtel"
password = "sercomtel"

[settings.config]
