[[carrier_id]]
mcc_mnc = "29403"

[settings]
version = 77000000002

[[settings.apns.apn]]
name = "internet"
value = "internet"
type = ["default", "supl"]
protocol = "ipv4v6"

[[settings.apns.apn]]
name = "MMS"
value = "mms"
type = ["mms"]
mmsc = "http://mmsc.a1.mk"

[[settings.apns.apn]]
name = "IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|20"
protocol = "ipv4v6"
user_visible = false

[[settings.apns.apn]]
name = "hos"
value = "hos"
type = ["xcap"]
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[settings.config]
carrier_supports_ss_over_ut = true
carrier_volte_available = true
hide_enhanced_4g_lte = true
maxImageHeight = 1944
maxImageWidth = 2592
maxMessageSize = 256000

[settings.config.imsemergency]
emergency_over_ims_supported_rats = [3]

[settings.config.imsss]
xcap_over_ut_supported_rats = [5, 6, 3, 1, 2]

[settings.config.imsvoice.audio_codec_capability_payload_types]
amrnb_payload_type = [98, 103]
amrwb_payload_type = [100, 105]
dtmfnb_payload_type = [97]
dtmfwb_payload_type = [96]

[settings.field8]
seconds = 1752062637
