[[carrier_id]]
mcc_mnc = "29340"

[settings]
version = 77000000003

[[settings.apns.apn]]
name = "Si.mobil GPRS"
value = "internet.simobil.si"
type = ["default", "supl"]
user = "simobil"
password = "internet"
authtype = 1
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "Si.mobil MMS"
value = "mms.simobil.si"
type = ["mms"]
user = "simobil"
password = "internet"
authtype = 1
mmsc = "http://mmc/"
mmsc_proxy = "80.95.224.46"
mmsc_proxy_port = "9201"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|18|20"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[[settings.apns.apn]]
name = "hos"
value = "hos"
type = ["xcap"]
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[settings.config]
carrier_supports_ss_over_ut = true
carrier_volte_available = true
carrier_wfc_ims_available = true
hide_enhanced_4g_lte = true
ignore_rtt_mode_setting = true
prefer_3g_visibility = false
rtt_downgrade_supported = true
rtt_supported = true
rtt_supported_while_roaming = true
show_4g_for_lte_data_icon = true
wfc_spn_format_idx = 1

[settings.config.imsemergency]
emergency_domain_preference = [2, 1]
emergency_domain_preference_roaming = [2, 1]
emergency_over_ims_supported_rats = [3]

[settings.config.imsss]
xcap_over_ut_supported_rats = [6, 3, 5, 1, 2]

[settings.config.imsvoice]
ringback_timer_millis = 120000
ringing_timer_millis = 120000

[settings.config.iwlan]
diffie_hellman_groups = [14]
ike_device_identity_supported = true

[settings.field8]
seconds = 1739349361
