[[carrier_id]]
mcc_mnc = "334140"

[carrier_id.mvno_data]
kind = "spn"
value = "CHAMO-MOVIL"

[[carrier_id]]
mcc_mnc = "334140"

[carrier_id.mvno_data]
kind = "spn"
value = "BYPLUS"

[[settings.apns.apn]]
name = "Adinteli"
value = "internet.plus.com"
type = ["default"]

[[settings.apns.apn]]
name = "Adinteli"
value = "ims"
type = ["ims"]

[settings.config]
