[[carrier_id]]
mcc_mnc = "334140"

[carrier_id.mvno_data]
kind = "spn"
value = "MISTRAL"

[[settings.apns.apn]]
name = "Adm"
value = "internet.adm.com"
type = ["default"]

[[settings.apns.apn]]
name = "Adm"
value = "ims"
type = ["ims"]

[settings.config]
