[[carrier_id]]
mcc_mnc = "52001"

[[carrier_id]]
mcc_mnc = "52003"

[settings]
version = 77000000004

[[settings.apns.apn]]
name = "AIS Internet"
value = "internet"
type = ["default", "supl"]
authtype = 0

[[settings.apns.apn]]
name = "AIS MMS"
value = "multimedia"
type = ["mms"]
mmsc = "http://mms.mobilelife.co.th"
mmsc_proxy = "203.170.229.34"
mmsc_proxy_port = "8080"

[[settings.apns.apn]]
name = "IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|18|20"
protocol = "ipv6"
roaming_protocol = "ipv4v6"
user_visible = false

[settings.config]
carrier_default_2g_protection_enabled = true
carrier_default_wfc_ims_mode = 1
carrier_volte_available = true
roaming_operator = ["520"]
show_4g_for_lte_data_icon = true
wfc_spn_format_idx = 1

[settings.config.imsemergency]
emergency_domain_preference = [2, 1]
emergency_domain_preference_roaming = [2, 1]
emergency_over_ims_supported_rats = [3]

[settings.config.imsss]
xcap_over_ut_supported_rats = []

[settings.config.imsvoice]
conference_factory_uri = "conf@ims.mnc003.mcc520.3gppnetwork.org"

[settings.config.imsvoice.audio_codec_capability_payload_types]
amrnb_payload_type = [98, 103]
amrwb_payload_type = [100, 105]
dtmfnb_payload_type = [97]
dtmfwb_payload_type = [96]

[settings.field8]
seconds = 1772636232
