[[carrier_id]]
mcc_mnc = "24414"

[carrier_id.mvno_data]
kind = "spn"
value = "ALCOM"

[[carrier_id]]
mcc_mnc = "24414"

[settings]
version = 77000000002

[[settings.apns.apn]]
name = "Internet"
value = "internet"
type = ["default"]
authtype = 0
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|20"
user_visible = false

[[settings.apns.apn]]
name = "mms"
value = "mms"
type = ["mms"]
authtype = 1
mmsc = "http://mms.amt.aland.fi"
mmsc_proxy = "194.110.177.70"
mmsc_proxy_port = "8080"
user_visible = false

[settings.config]
carrier_volte_available = true

[settings.config.imsemergency]
emergency_domain_preference = [2, 1]
emergency_domain_preference_roaming = [2, 1]

[settings.config.imsvoice.audio_codec_capability_payload_types]
amrnb_payload_type = [98, 103]
amrwb_payload_type = [100, 105]
dtmfnb_payload_type = [97]
dtmfwb_payload_type = [96]

[settings.field8]
seconds = 1737535040
