[[carrier_id]]
mcc_mnc = "208090"

[carrier_id.mvno_data]
kind = "imsi"
value = "208090057"

[[carrier_id]]
mcc_mnc = "208090"

[carrier_id.mvno_data]
kind = "imsi"
value = "208090058"

[[carrier_id]]
mcc_mnc = "208090"

[carrier_id.mvno_data]
kind = "imsi"
value = "208090059"

[[carrier_id]]
mcc_mnc = "208090"

[carrier_id.mvno_data]
kind = "imsi"
value = "208090060"

[[carrier_id]]
mcc_mnc = "208090"

[carrier_id.mvno_data]
kind = "imsi"
value = "208090061"

[settings]
version = 77000000002

[[settings.apns.apn]]
name = "Optimum Internet"
value = "altice"
type = ["default", "supl", "fota"]
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_editable = false

[[settings.apns.apn]]
name = "Optimum MMS"
value = "mms"
type = ["mms"]
mmsc = "http://mms.altice.com/mmsc/MMS"
user_editable = false

[[settings.apns.apn]]
name = "IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|18|20"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[[settings.apns.apn]]
name = "xcap"
value = "xcap"
type = ["xcap"]
bearer_bitmask = "14|18|20"
user_visible = false

[settings.config]
allow_metered_network_for_cert_download = true
hide_enhanced_4g_lte = true
ignore_rtt_mode_setting = true
imsi_key_availability = 2
imsi_key_download_url = "https://ws.alticemobile.com/carrier/keys/publickey"
wfc_spn_format_idx = 1

[settings.config.bsf]
bsf_server_fqdn = "ap.ims.mnc390.mcc313.3gppnetwork.org"
bsf_server_port = 81

[settings.config.imsemergency]
emergency_domain_preference = [2, 1]
emergency_domain_preference_roaming = [2, 1]
emergency_over_ims_supported_rats = [3]
emergency_registration_timer_millis = 10000

[settings.config.imsrtt]
text_on_default_bearer_supported = true

[settings.config.imsss]
ut_as_server_fqdn = "xcap.ims.mnc390.mcc313.3gppnetwork.org"
ut_iptype_home = 0
ut_iptype_roaming = 0
xcap_over_ut_supported_rats = [6, 3, 5]

[settings.config.imsvoice]
include_caller_id_service_codes_in_sip_invite = true

[settings.config.imsvoice.evs_payload_description.127]
evs_codec_attribute_bitrate = [4, 4]
evs_codec_attribute_ch_aw_recv = 2

[settings.config.iwlan]
add_ke_to_child_session_rekey = true
diffie_hellman_groups = [14]
epdg_address_priority = [0]
epdg_static_address = "EPDG.EPC.mnc390.mcc313.pub.3gppnetwork.org"
ike_rekey_hard_timer_in_sec = 43200
ike_rekey_soft_timer_sec = 43100

[settings.config.wifi]
carrier_profiles_version = 1
passpoint_profiles = ['<?xml version="1.0" encoding="UTF-8"?><PasspointProfile><PPSMO><![CDATA[<MgmtTree xmlns="syncml:dmddf1.2"><VerDTD>1.2</VerDTD><Node><NodeName>PerProviderSubscription</NodeName><RTProperties><Type><DDFName>urn:wfa:mo:hotspot2dot0-perprovidersubscription:1.0</DDFName></Type></RTProperties><Node><NodeName>i001</NodeName><Node><NodeName>HomeSP</NodeName><Node><NodeName>FriendlyName</NodeName><Value>Optimum</Value></Node><Node><NodeName>FQDN</NodeName><Value>alticemobile.com</Value></Node></Node><Node><NodeName>Credential</NodeName><Node><NodeName>Realm</NodeName><Value>passpoint.alticemobile.com</Value></Node><Node><NodeName>SIM</NodeName><Node><NodeName>IMSI</NodeName><Value>313390*</Value></Node><Node><NodeName>EAPType</NodeName><Value>23</Value></Node></Node></Node></Node></Node></MgmtTree>]]></PPSMO></PasspointProfile>']

[settings.field8]
seconds = 1761090366
