[[carrier_id]]
mcc_mnc = "21303"

[settings]
version = 77000000002

[[settings.apns.apn]]
name = "Internet"
value = "internet"
type = ["default", "supl"]
user_editable = false

[[settings.apns.apn]]
name = "IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|18|20"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[[settings.apns.apn]]
name = "hos"
value = "hos"
type = ["xcap"]
user_visible = false

[settings.config]
carrier_supports_ss_over_ut = true
carrier_volte_available = true
carrier_wfc_ims_available = true
hide_enhanced_4g_lte = true
wfc_spn_format_idx = 1

[settings.config.bsf]
bsf_server_fqdn = "bsf.ims.mnc003.mcc213.3gppnetwork.org"
bsf_server_port = 8088

[settings.config.imsemergency]
emergency_domain_preference = [2, 1]
emergency_domain_preference_roaming = [2, 1]
emergency_over_ims_supported_rats = [3]

[settings.config.imsss]
ut_as_server_fqdn = "xcap.ims.mnc003.mcc213.3gppnetwork.org"
ut_as_server_port = 8080
xcap_over_ut_supported_rats = [6, 3, 5, 1, 2]

[settings.config.imsvoice.audio_codec_capability_payload_types]
amrnb_payload_type = [98, 103]
amrwb_payload_type = [100, 105]
dtmfnb_payload_type = [97]
dtmfwb_payload_type = [96]

[settings.config.iwlan]
diffie_hellman_groups = [14]

[settings.field8]
seconds = 1752617339
