[[carrier_id]]
mcc_mnc = "310240"

[carrier_id.mvno_data]
kind = "gid1"
value = "8135"

[[carrier_id]]
mcc_mnc = "310260"

[carrier_id.mvno_data]
kind = "gid1"
value = "8135"

[settings]
version = 77000000009

[[settings.apns.apn]]
name = "Bark"
value = "wholesale"
type = ["default", "supl", "mms"]
mmsc = "http://wholesale.mmsmvno.com/mms/wapenc"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_editable = false

[[settings.apns.apn]]
name = "Bark Tethering"
value = "hotspot"
type = ["dun"]
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[[settings.apns.apn]]
name = "IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|18|20"
protocol = "ipv6"
roaming_protocol = "ipv4v6"
mtu = 1440
user_visible = false
field28 = 1

[[settings.apns.apn]]
name = "Emergency"
value = "sos"
type = ["emergency"]
protocol = "ipv6"
roaming_protocol = "ipv4v6"
user_visible = false
field28 = 1

[settings.config]
_5g_icon_configuration = "connected_mmwave:5G_Plus,connected:5G,not_restricted_rrc_idle:5G,not_restricted_rrc_con:5G"
_5g_icon_display_grace_period = "connected_mmwave,legacy,30;connected_mmwave,connected,30;connected_mmwave,not_restricted_rrc_idle,30;connected_mmwave,not_restricted_rrc_con,30;connected,legacy,30;not_restricted_rrc_idle,legacy,30;not_restricted_rrc_con,legacy,30"
_5g_nr_ssrsrp_thresholds = [-120, -114, -109, -100]
additional_nr_advanced_bands = [25, 41, 48, 66, 71, 77, 258, 260, 261]
call_composer_picture_server_url = ""
carrier_certificate = []
carrier_default_data_roaming_enabled = true
carrier_default_wfc_ims_enabled = true
carrier_default_wfc_ims_mode = 1
carrier_default_wfc_ims_roaming_enabled = true
carrier_default_wfc_ims_roaming_mode = 2
carrier_ims_gba_required = true
carrier_nr_availabilities = [1, 2]
carrier_supports_ss_over_ut = true
carrier_ussd_method = 1
carrier_volte_available = true
carrier_vowifi_tty_supported = false
carrier_vt_available = false
carrier_wfc_ims_available = true
data_connected_roaming_notification_excluded_mccs = ["310", "311", "312", "313", "314", "315", "316"]
data_connected_roaming_notification_included_mcc_mncs = ["310032", "310033", "310110", "310140", "310370", "310400", "310470", "310500", "310970", "311170", "311250"]
data_limit_threshold_bytes = 107374182400
disconnect_cause_network_busy = [60]
display_hd_plus_icon = true
editable_voicemail_number_setting = false
emergency_number_prefix = ["*272"]
enable_carrier_display_name_resolver = true
enable_nr_advanced_for_roaming = true
gba_ua_tls_cipher_suite = 47
gsm_roaming_networks = ["310032", "310033", "310110", "310140", "310370", "310400", "310470", "310500", "310970", "311170", "311250"]
hide_enhanced_4g_lte = true
hide_tty_hco_vco_with_rtt = true
ignore_rtt_mode_setting = true
ims_reasoninfo_mapping = ["510|Call completed elsewhere|1014", "*|Call is dropped due to Wi-Fi signal is degraded|1407"]
inflate_signal_strength = true
iwlan_handover_policy = ["source=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN|UNKNOWN, target=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN, type=disallowed, capabilities=EIMS|MMS|XCAP|CBS", "source=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN|UNKNOWN, target=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN, roaming=true, type=disallowed, capabilities=IMS", "source=IWLAN|UNKNOWN, target=GERAN|UTRAN, type=disallowed, capabilities=IMS", "source=GERAN|UTRAN, target=IWLAN, type=disallowed, capabilities=IMS", "source=EUTRAN|NGRAN|IWLAN, target=EUTRAN|NGRAN|IWLAN, type=allowed, capabilities=IMS"]
lte_rsrp_thresholds = [-120, -114, -109, -100]
maxImageHeight = 1944
maxImageWidth = 2592
maxMessageSize = 1048576
min_udp_port_4500_nat_timeout_sec = 1680
mmi_two_digit_number_pattern = ["*2"]
mmsCloseConnection = true
nr_advanced_threshold_bandwidth_khz = 40000
nr_timers_reset_on_voice_qos = true
prefer_2g = true
preferred_ike_protocol = 40
ratchet_nr_advanced_bandwidth_if_rrc_idle = true
read_only_apn_types = []
recipientLimit = 20
rtt_downgrade_supported = true
rtt_supported = true
rtt_supported_while_roaming = true
show_data_connected_roaming_notification = true
show_roaming_indicator = false
smsToMmsTextThreshold = 12
support_video_conference_call = false
volte_replacement_rat = 3
vonr_enabled = true
wfc_carrier_name_override_by_pnn = true
wfc_operator_error_codes = ["REG09|0"]
wfc_spn_format_idx = 1

[settings.config.bsf]
bsf_server_fqdn = "bsf.msg.pc.t-mobile.com"
bsf_server_port = 443
bsf_transport_type = 3

[settings.config.ims]
enable_presence_capability_exchange = false
enable_presence_publish = false
geolocation_pidf_in_sip_invite_support = [4, 2]
geolocation_pidf_in_sip_register_support = [4, 2]
gruu_enabled = true
ims_user_agent = "T-Mobile EPSFB-ePDG-IR94-RTT-ussd #MANUFACTURE#/#MODEL# #BUILD#"
request_uri_type = 1

[settings.config.imsemergency]
emergency_lte_preferred_after_nr_failed = true
emergency_over_ims_roaming_supported_3gpp_network_types = [6, 3]
emergency_over_ims_supported_3gpp_network_types = [6, 3]
emergency_over_ims_supported_rats = [6, 3, 5]
emergency_registration_timer_millis = 10000
emergency_scan_timer_sec = 50
retry_emergency_on_ims_pdn = true

[settings.config.imsss]
network_initiated_ussd_over_ims_supported = false
ut_as_server_fqdn = "xcap.msg.pc.t-mobile.com"
ut_as_server_port = 443
ut_server_based_services = [20, 12, 18, 14, 19, 21, 15, 16, 17, 13, 1, 3, 4, 7, 6, 5, 2, 0, 8, 9, 11]
ut_terminal_based_services = [10]
ut_transport_type = 3
xcap_over_ut_supported_rats = [6, 3, 5, 1, 2]

[settings.config.imsvoice]
audio_inactivity_call_end_reasons = [0, 1, 2]
audio_rtcp_inactivity_timer_millis = 30000
audio_rtp_inactivity_timer_millis = 30000
conference_factory_uri = "8881112663@msg.pc.t-mobile.com"
dedicated_bearer_wait_timer_millis = 40000
include_caller_id_service_codes_in_sip_invite = true
mo_call_request_timeout_millis = 0
ringback_timer_millis = 128000
rtp_packet_loss_rate_threshold = 30
voice_on_default_bearer_supported = true

[settings.config.imsvoice.evs_payload_description.127]
evs_codec_attribute_bitrate = [0, 4]
evs_codec_attribute_ch_aw_recv = 2

[settings.config.imsvt]
video_as_bandwidth_kbps = 560
video_rs_bandwidth_bps = 5200
video_rtp_dscp = 34

[settings.config.iwlan]
diffie_hellman_groups = [14]
epdg_address_priority = [0, 1]
epdg_plmn_priority = [3, 1]
epdg_static_address = "epdg.epc.mnc260.mcc310.pub.3gppnetwork.org"
ike_session_encryption_aes_cbc_key_size = [128, 256]
key_error_policy_config = '[{"ApnName": "*","ErrorTypes": [{"ErrorType": "IKE_PROTOCOL_ERROR_TYPE","ErrorDetails": ["10500"],"RetryArray": ["3600","7200","10800"],"UnthrottlingEvents": ["APM_ENABLE_EVENT","WIFI_DISABLE_EVENT","WIFI_CALLING_DISABLE_EVENT"]},{"ErrorType": "IKE_PROTOCOL_ERROR_TYPE","ErrorDetails": ["15500"],"NumAttemptsPerFqdn": "6","RetryArray": ["0","0","300","600","1200","0","0","0","300","600","1200","-1"],"UnthrottlingEvents": ["APM_ENABLE_EVENT","WIFI_DISABLE_EVENT","WIFI_CALLING_DISABLE_EVENT"]},{"ErrorType": "IKE_PROTOCOL_ERROR_TYPE","ErrorDetails": ["11001","11011"],"RetryArray": [],"UnthrottlingEvents": []},{"ErrorType": "IKE_PROTOCOL_ERROR_TYPE","ErrorDetails": ["8192"],"RetryArray": ["5","10","10","20","40","80","160","320","640","1280","1800","3600","-1"],"UnthrottlingEvents": ["APM_ENABLE_EVENT","WIFI_DISABLE_EVENT","WIFI_CALLING_DISABLE_EVENT"],"HandoverAttemptCount": "3"}]}]'
supported_integrity_algorithms = [5, 12]
supported_prf_algorithms = [2, 4, 5]
supports_child_session_multiple_sa_proposals = false
supports_ike_session_multiple_sa_proposals = false

[settings.config.qns]
idle_eutran_rsrp = [-109, -114]
idle_geran_rssi = [-95, -105]
idle_ngran_ssrsrp = [-109, -114]
idle_utran_ecno = [-10, -15]
idle_utran_rscp = [-100, -110]
idle_wifi_rssi = [-70, -80]
ims_wlan_hysteresis_timer_ms = [10000, 10000, 10000]
ims_wwan_hysteresis_timer_ms = [10000, 10000, 10000]
mms_rat_preference = 2
video_eutran_rsrp = [-109, -114]
video_ngran_ssrsrp = [-109, -114]
video_wifi_rssi = [-70, -80]
voice_eutran_rsrp = [-109, -114]
voice_ngran_ssrsrp = [-109, -114]
voice_wifi_rssi = [-70, -80]

[settings.config.wifi]
avoid_5ghz_softap_for_laa = true
avoid_5ghz_wifi_direct_for_laa = true
carrier_profiles_version = 2
passpoint_profiles = []

[settings.field8]
seconds = 1777512376
