[[carrier_id]]
mcc_mnc = "21901"

[carrier_id.mvno_data]
kind = "gid1"
value = "10"

[[carrier_id]]
mcc_mnc = "21901"

[carrier_id.mvno_data]
kind = "gid1"
value = "11"

[[carrier_id]]
mcc_mnc = "21901"

[carrier_id.mvno_data]
kind = "gid1"
value = "12"

[[carrier_id]]
mcc_mnc = "21901"

[carrier_id.mvno_data]
kind = "spn"
value = "BONBON"

[settings]
version = 77000000001

[[settings.apns.apn]]
name = "Internet"
value = "internet.ht.hr"
type = ["default", "supl", "dun", "fota"]
authtype = 1
user_editable = false

[[settings.apns.apn]]
name = "MMS"
value = "mms.htgprs"
type = ["mms"]
authtype = 1
mmsc = "http://mms.bonbon.com.hr/servlets/mms"
mmsc_proxy = "10.12.0.4"
mmsc_proxy_port = "8080"

[settings.config]
display_hd_audio_property = false
mmi_two_digit_number_pattern = ["92", "93", "94", "95", "96"]

[settings.field8]
seconds = 1762783759
