[[carrier_id]]
mcc_mnc = "28204"

[carrier_id.mvno_data]
kind = "spn"
value = "Cellfie"

[[carrier_id]]
mcc_mnc = "28204"

[settings]
version = 77000000001

[[settings.apns.apn]]
name = "Cellfie Mobile Internet"
value = "internet"
type = ["default"]
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "Cellfie Mobile IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|20"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[settings.config]
carrier_volte_available = true
ignore_rtt_mode_setting = true
rtt_downgrade_supported = true
rtt_supported = true
rtt_supported_while_roaming = true

[settings.field8]
seconds = 1740426872
