[[carrier_id]]
mcc_mnc = "334140"

[carrier_id.mvno_data]
kind = "spn"
value = "CFE TEIPT"

[[settings.apns.apn]]
name = "CFE"
value = "internet.cfe.com"
type = ["default"]

[[settings.apns.apn]]
name = "CFE"
value = "ims"
type = ["ims"]

[settings.config]
