[[carrier_id]]
mcc_mnc = "405912"

[[carrier_id]]
mcc_mnc = "405913"

[[carrier_id]]
mcc_mnc = "405914"

[[carrier_id]]
mcc_mnc = "405917"

[[settings.apns.apn]]
name = "Cheers"
value = "internet"
type = ["default", "supl"]
protocol = "ipv4v6"

[settings.config]
roaming_operator = ["404", "405"]
