[[carrier_id]]
mcc_mnc = "302150"

[carrier_id.mvno_data]
kind = "gid1"
value = "FFFF"

[settings]
version = 77000000001

[[settings.apns.apn]]
name = "Cogeco Internet"
value = "data.cogeco"
type = ["default"]
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_editable = false

[[settings.apns.apn]]
name = "Cogeco MMS"
value = "mms.cogeco"
type = ["mms"]
mmsc = "http://mms.cogeco.ca/"
mmsc_proxy = "10.232.12.49"
mmsc_proxy_port = "8080"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_editable = false

[[settings.apns.apn]]
name = "IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|20"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[settings.config]
carrier_volte_available = true
hide_enhanced_4g_lte = true
maxImageHeight = 1944
maxImageWidth = 2592
maxMessageSize = 1048576
maxSubjectLength = 80
recipientLimit = 20
smsToMmsTextThreshold = 6

[settings.config.gps]
es_extension_sec = "300"

[settings.config.imsemergency]
emergency_domain_preference = [2, 1]
emergency_domain_preference_roaming = [2, 1]
emergency_over_ims_supported_rats = [3]
emergency_registration_timer_millis = 10000

[settings.config.imsvoice.audio_codec_capability_payload_types]
amrnb_payload_type = [98, 103]
amrwb_payload_type = [100, 105]
dtmfnb_payload_type = [97]
dtmfwb_payload_type = [96]

[settings.field8]
seconds = 1756887206
