[[carrier_id]]
mcc_mnc = "26802"

[carrier_id.mvno_data]
kind = "spn"
value = "Digi PT"

[settings]
version = 77000000004

[[settings.apns.apn]]
name = "Digi PT"
value = "internet"
type = ["default", "supl", "ia", "dun", "hipri"]
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|18|20"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[settings.config]
carrier_volte_available = true
carrier_wfc_ims_available = true
ignore_rtt_mode_setting = true
read_only_apn_types = []
rtt_downgrade_supported = true
rtt_supported = true
rtt_supported_while_roaming = true

[settings.field8]
seconds = 1762278924
