[[carrier_id]]
mcc_mnc = "334140"

[carrier_id.mvno_data]
kind = "spn"
value = "NEMI"

[[settings.apns.apn]]
name = "Diveracy"
value = "internet.diveracy.com"
type = ["default"]

[[settings.apns.apn]]
name = "Diveracy"
value = "ims"
type = ["ims"]

[settings.config]
