[[carrier_id]]
mcc_mnc = "42403"

[settings]
version = 77000000002

[[settings.apns.apn]]
name = "du"
value = "du"
type = ["default", "supl", "mms"]
mmsc = "http://mms.du.ae:8002"
protocol = "ipv4v6"

[[settings.apns.apn]]
name = "IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|20"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[[settings.apns.apn]]
name = "Du XCAP"
value = "xcap"
type = ["xcap"]
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[settings.config]
carrier_supports_ss_over_ut = true
carrier_ussd_method = 1
carrier_volte_available = true

[settings.config.imsemergency]
emergency_domain_preference = [2, 1]
emergency_domain_preference_roaming = [2, 1]
emergency_over_ims_supported_rats = [3]

[settings.config.imsss]
xcap_over_ut_supported_rats = [6, 3, 5, 1, 2]

[settings.config.imsvoice.audio_codec_capability_payload_types]
amrnb_payload_type = [98, 103]
amrwb_payload_type = [100, 105]
dtmfnb_payload_type = [97]
dtmfwb_payload_type = [96]

[settings.field8]
seconds = 1739349361
