[[carrier_id]]
mcc_mnc = "23430"

[[carrier_id]]
mcc_mnc = "23433"

[[carrier_id]]
mcc_mnc = "23486"

[settings]
version = 77000000006

[[settings.apns.apn]]
name = "IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|18|20"
user = "eesecure"
password = "secure"
authtype = 1
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[[settings.apns.apn]]
name = "EE Internet"
value = "everywhere"
type = ["default", "supl"]
user = "eesecure"
password = "secure"
authtype = 1
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_editable = false

[[settings.apns.apn]]
name = "EE MMS"
value = "eezone"
type = ["mms", "xcap"]
user = "eesecure"
password = "secure"
authtype = 1
mmsc = "http://mms/"
mmsc_proxy = "149.254.201.135"
mmsc_proxy_port = "8080"
user_editable = false

[[settings.apns.apn]]
name = "EE Emergency"
value = "sos"
type = ["emergency"]
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[settings.config]
carrier_cross_sim_ims_available = false
carrier_default_data_roaming_enabled = true
carrier_name = "EE"
carrier_name_override = true
carrier_nr_availabilities = [1, 2]
carrier_supports_ss_over_ut = true
carrier_ussd_method = 2
carrier_volte_available = true
carrier_wfc_ims_available = true
display_voicemail_number_as_default_call_forwarding_number = true
editable_enhanced_4g_lte = false
editable_wfc_mode = false
hide_enhanced_4g_lte = true
hide_ims_apn = true
hide_preferred_network_type = true
iwlan_handover_policy = ["source=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN|UNKNOWN, target=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN, type=disallowed, capabilities=MMS|XCAP|CBS", "source=GERAN|UTRAN|EUTRAN|NGRAN|UNKNOWN, target=IWLAN, type=disallowed, capabilities=EIMS", "source=IWLAN|UNKNOWN, target=GERAN|UTRAN, type=disallowed, capabilities=EIMS", "source=IWLAN, target=EUTRAN|NGRAN, type=allowed, capabilities=EIMS", "source=IWLAN|UNKNOWN, target=GERAN|UTRAN, type=disallowed, capabilities=IMS", "source=GERAN|UTRAN, target=IWLAN, type=disallowed, capabilities=IMS", "source=EUTRAN|NGRAN|IWLAN, target=EUTRAN|NGRAN|IWLAN, type=allowed, capabilities=IMS"]
non_roaming_operator = ["23430", "23431", "23432", "23433", "23434", "23486"]
prefer_2g = false
preferred_ike_protocol = 40
show_4g_for_lte_data_icon = true
use_wfc_home_network_mode_in_roaming_network = true
vonr_enabled = true
vonr_setting_visibility = false
wfc_operator_error_codes = ["REG09|0"]
wfc_spn_format_idx = 1

[settings.config.ims]
geolocation_pidf_in_sip_invite_support = [4, 2]
geolocation_pidf_in_sip_register_support = [4, 2]
ims_user_agent = "#MANUFACTURE#_#MODEL#_#BUILD#"
ipv4_sip_mtu_size_cellular = 1200
ipv6_sip_mtu_size_cellular = 1200
sip_timer_f_millis = 32000
sip_timer_j_millis = 32000

[settings.config.imsemergency]
emergency_over_ims_roaming_supported_3gpp_network_types = [6, 3]
emergency_over_ims_supported_3gpp_network_types = [6, 3]
emergency_over_ims_supported_rats = [6, 3, 5]
prefer_ims_emergency_when_voice_calls_on_cs = true

[settings.config.imsss]
network_initiated_ussd_over_ims_supported = false
ut_iptype_home = 0
ut_iptype_roaming = 0
xcap_over_ut_supported_rats = [5, 6, 3, 1, 2]

[settings.config.imsvoice]
conference_subscribe_type = 0
minimum_session_expires_timer_sec = 600
ringback_timer_millis = 130000
ringing_timer_millis = 60000

[settings.config.imsvoice.audio_codec_capability_payload_types]
amrnb_payload_type = [102]
amrwb_payload_type = [104]
dtmfnb_payload_type = [97]
dtmfwb_payload_type = [96]
evs_payload_type = [127]

[settings.config.imsvoice.evs_payload_description.127]
evs_codec_attribute_bitrate = [0, 6]
evs_codec_attribute_ch_aw_recv = 2

[settings.config.imswfc]
emergency_call_over_emergency_pdn = true

[settings.config.iwlan]
ike_rekey_hard_timer_in_sec = 1300
ike_rekey_soft_timer_sec = 1200
key_error_policy_config = '[{"ApnName": "*","ErrorTypes": [{"ErrorType": "IKE_PROTOCOL_ERROR_TYPE","ErrorDetails": ["24"],"RetryArray": ["10", "30", "60", "120", "300", "-1"],"UnthrottlingEvents": ["APM_ENABLE_EVENT", "WIFI_DISABLE_EVENT", "WIFI_AP_CHANGED_EVENT", "WIFI_CALLING_DISABLE_EVENT"]}]}]'

[settings.config.qns]
mms_rat_preference = 2
sos_transport_type = 2
xcap_rat_preference = 2

[settings.field8]
seconds = 1768403337
