[[carrier_id]]
mcc_mnc = "738040"

[settings]
version = 77000000001

[[settings.apns.apn]]
name = "Enet"
value = "enet"
type = ["default", "supl"]
bearer_bitmask = "14|20"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|20"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[settings.config]
carrier_volte_available = true

[settings.field8]
seconds = 1733311844
