[[carrier_id]]
mcc_mnc = "732103"

[carrier_id.mvno_data]
kind = "spn"
value = "ETB MOVI"

[[carrier_id]]
mcc_mnc = "732111"

[carrier_id.mvno_data]
kind = "spn"
value = "ETB MOVIL"

[[settings.apns.apn]]
name = "Internet ETB"
value = "moviletb.net.co"
type = ["default", "dun"]
user = "etb"
password = "etb"
authtype = 0
user_editable = false

[settings.config]
