[[carrier_id]]
mcc_mnc = "302500"

[carrier_id.mvno_data]
kind = "gid1"
value = "55"

[settings]
version = 77000000009

[[settings.apns.apn]]
name = "mobile.bm"
value = "mobile.bm"
type = ["default", "mms", "supl"]
mmsc = "http://mms.mobile.bm"
mmsc_proxy = "mmsproxy.mobile.bm"
mmsc_proxy_port = "80"
user_editable = false

[[settings.apns.apn]]
name = "LTE IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|18|20"
protocol = "ipv6"
roaming_protocol = "ipv6"
user_visible = false
user_editable = false

[[settings.apns.apn]]
name = "LTE XCAP"
value = "xcap"
type = ["xcap"]
user_visible = false
user_editable = false

[[settings.apns.apn]]
name = "Emergency"
value = "sos"
type = ["emergency"]
protocol = "ipv6"
roaming_protocol = "ipv6"
user_visible = false

[settings.config]
_5g_icon_configuration = "connected_mmwave:5G_Plus,connected:5G,not_restricted_rrc_idle:5G,not_restricted_rrc_con:5G"
additional_nr_advanced_bands = [77, 78]
carrier_cross_sim_ims_available = false
carrier_supports_ss_over_ut = true
carrier_ussd_method = 2
carrier_volte_available = true
dial_string_replace = ["611:+15146470998", "*611:+15146470998", "#611:+15146470998", "411:+15146470990", "*411:+15146470990", "#411:+15146470990"]
editable_enhanced_4g_lte = false
hide_lte_plus_data_icon = false
ims_reasoninfo_mapping = ["510|Call completed elsewhere|1014", "*|Call is dropped due to Wi-Fi signal is degraded|1407"]
is_ims_conference_size_enforced = true
iwlan_handover_policy = ["source=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN|UNKNOWN, target=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN, type=disallowed, capabilities=EIMS|MMS|XCAP|CBS", "source=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN|UNKNOWN, target=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN, roaming=true, type=disallowed, capabilities=IMS", "source=IWLAN|UNKNOWN, target=GERAN|UTRAN, type=disallowed, capabilities=IMS", "source=GERAN|UTRAN, target=IWLAN, type=disallowed, capabilities=IMS", "source=EUTRAN|NGRAN|IWLAN, target=EUTRAN|NGRAN|IWLAN, type=allowed, capabilities=IMS"]
lte_plus_threshold_bandwidth_khz = 0
maxImageHeight = 1944
maxImageWidth = 2592
maxMessageSize = 3072000
maxSubjectLength = 80
non_roaming_operator = ["302"]
prefer_3g_visibility = false
read_only_apn_types = []
recipientLimit = 20
smsToMmsTextThreshold = 6
support_no_reply_timer_for_cfnry = false
use_wfc_home_network_mode_in_roaming_network = true
volte_replacement_rat = 3
wfc_emergency_address_carrier_app = "com.google.android.wfcactivation/.WfcActivationCanadaActivity"
wfc_spn_format_idx = 1

[settings.config.bsf]
bsf_server_port = 8080

[settings.config.gps]
es_extension_sec = "300"

[settings.config.ims]
ims_user_agent = "Videotron #MODEL# #BUILD#"
sip_timer_f_millis = 32000
sip_timer_j_millis = 32000

[settings.config.imsemergency]
emergency_domain_preference = [2, 1]
emergency_domain_preference_roaming = [2, 1]
emergency_over_ims_supported_rats = [3]
emergency_registration_timer_millis = 10000
emergency_scan_timer_sec = 10
maximum_cellular_search_timer_sec = 10
prefer_ims_emergency_when_voice_calls_on_cs = true

[settings.config.imsss]
network_initiated_ussd_over_ims_supported = false
ut_as_server_port = 8090
ut_iptype_home = 0
ut_iptype_roaming = 0
xcap_over_ut_supported_rats = [5, 6, 3, 1, 2]

[settings.config.imsvoice]
conference_factory_uri = "conference@factory.ims.mnc500.mcc302.3gppnetwork.org"
minimum_session_expires_timer_sec = 600
prack_supported_for_18x = true
srvcc_type = []

[settings.config.imsvoice.amrnb_payload_description.108]
amr_codec_attribute_payload_format = 1

[settings.config.imsvoice.amrwb_payload_description.110]
amr_codec_attribute_payload_format = 1

[settings.config.imswfc]
emergency_call_over_emergency_pdn = true

[settings.config.qns]
idle_eutran_rsrp = [-114, -120]
idle_utran_rscp = [-103, -110]
idle_wifi_rssi = [-74, -80]
plmn_list_regarded_as_roaming = ["302490"]
sos_transport_type = 2
video_eutran_rsrp = [-114, -120]
video_utran_rscp = [-103, -110]
video_wifi_rssi = [-74, -80]
voice_eutran_rsrp = [-114, -120]
voice_utran_rscp = [-103, -110]
voice_wifi_rssi = [-74, -80]

[settings.field8]
seconds = 1770819167
