[[carrier_id]]
mcc_mnc = "23410"

[carrier_id.mvno_data]
kind = "gid1"
value = "50"

[[carrier_id]]
mcc_mnc = "23410"

[carrier_id.mvno_data]
kind = "spn"
value = "GIFFGAFF"

[settings]
version = 77000000004

[[settings.apns.apn]]
name = "giffgaff"
value = "giffgaff.com"
type = ["default", "mms"]
user = "gg"
password = "p"
authtype = 1
mmsc = "http://mmsc.mediamessaging.co.uk:8002"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|18|20"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[settings.config]
carrier_default_wfc_ims_enabled = true
carrier_default_wfc_ims_mode = 1
carrier_supports_ss_over_ut = true
carrier_volte_available = true
carrier_wfc_ims_available = true
default_vm_number = "443"
hide_lte_plus_data_icon = false
non_roaming_operator = ["23420", "23426", "23430", "23431", "23432", "23433", "23434", "23486"]
prefer_2g = false
radio_restart_failure_causes = [55]
read_only_apn_types = []
show_4g_for_lte_data_icon = true
show_wifi_calling_icon_in_status_bar = true
smsToMmsTextThreshold = 10
wfc_spn_format_idx = 1

[settings.config.imsemergency]
prefer_ims_emergency_when_voice_calls_on_cs = true

[settings.config.iwlan]
diffie_hellman_groups = [14]

[settings.field8]
seconds = 1774646596
