[[carrier_id]]
mcc_mnc = "27821"

[settings]
version = 77000000006

[[settings.apns.apn]]
name = "GO"
value = "gointernet"
type = ["default", "supl"]
user_editable = false

[[settings.apns.apn]]
name = "IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|18|20"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[settings.config]
carrier_default_wfc_ims_enabled = true
carrier_default_wfc_ims_mode = 1
carrier_volte_available = true
carrier_wfc_ims_available = true
hide_enhanced_4g_lte = true
wfc_spn_format_idx = 1

[settings.config.imsvoice]
srvcc_type = [0, 1, 3]

[settings.config.iwlan]
diffie_hellman_groups = [14]

[settings.field8]
seconds = 1770819167
