[[carrier_id]]
mcc_mnc = "334140"

[carrier_id.mvno_data]
kind = "spn"
value = "Gurucomm"

[[settings.apns.apn]]
name = "Guruweb"
value = "internet.gugacom.com"
type = ["default"]

[[settings.apns.apn]]
name = "Guruweb"
value = "ims"
type = ["ims"]

[settings.config]
