[[carrier_id]]
mcc_mnc = "23205"

[[carrier_id]]
mcc_mnc = "23210"

[[carrier_id]]
mcc_mnc = "23214"

[settings]
version = 77000000013

[[settings.apns.apn]]
name = "Planet3"
value = "drei.at"
type = ["default", "mms", "supl"]
mmsc = "http://mmsc"
mmsc_proxy = "213.94.78.133"
mmsc_proxy_port = "8799"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "ims"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|18|20"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
mtu = 1500
user_visible = false

[[settings.apns.apn]]
name = "hos"
value = "hos"
type = ["xcap"]
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[settings.config]
call_barring_visibility = true
carrier_allow_transfer_ims_call = true
carrier_default_wfc_ims_enabled = true
carrier_default_wfc_ims_mode = 1
carrier_default_wfc_ims_roaming_enabled = true
carrier_default_wfc_ims_roaming_mode = 1
carrier_nr_availabilities = [2, 1]
carrier_supports_ss_over_ut = true
carrier_ussd_method = 1
carrier_volte_available = true
carrier_wfc_ims_available = true
editable_wfc_roaming_mode = true
hide_enhanced_4g_lte = true
ignore_rtt_mode_setting = true
non_roaming_operator = ["23203", "23205"]
prefer_3g_visibility = false
rtt_downgrade_supported = true
rtt_supported = true
rtt_supported_while_roaming = true
show_4g_for_lte_data_icon = true
vonr_enabled = true
vonr_setting_visibility = false
wfc_spn_format_idx = 3

[settings.config.ims]
registration_expiry_timer_sec = 36000
request_uri_type = 1

[settings.config.imsemergency]
emergency_over_ims_roaming_supported_3gpp_network_types = [6, 3]
emergency_over_ims_supported_3gpp_network_types = [6, 3]
emergency_over_ims_supported_rats = [6, 3, 5]

[settings.config.imsss]
ut_requires_ims_registration = true
ut_server_based_services = [12, 18, 14, 19, 21, 15, 16, 17, 13, 1, 3, 4, 7, 6, 5, 2, 8, 9, 11]
xcap_over_ut_supported_rats = [6, 3, 5, 1, 2]

[settings.config.imsvoice]
audio_inactivity_call_end_reasons = [2, 4]
audio_rtp_inactivity_timer_millis = 15000
conference_subscribe_type = 0
minimum_session_expires_timer_sec = 600
ringback_timer_millis = 120000
ringing_timer_millis = 120000

[settings.config.imsvoice.evs_payload_description.127]
evs_codec_attribute_bitrate = [0, 6]

[settings.config.imsvt]
video_as_bandwidth_kbps = 384
video_rr_bandwidth_bps = 14400
video_rs_bandwidth_bps = 4800

[settings.config.imswfc]
emergency_call_over_emergency_pdn = true

[settings.config.iwlan]
child_sa_rekey_hard_timer_sec = 3600
child_sa_rekey_soft_timer_sec = 1800
child_session_aes_cbc_key_size = [256]
diffie_hellman_groups = [14]
ike_rekey_hard_timer_in_sec = 3600
ike_rekey_soft_timer_sec = 1800
ike_session_encryption_aes_cbc_key_size = [256]
supported_integrity_algorithms = [14]
supported_prf_algorithms = [5, 7]

[settings.config.qns]
condition_rove_in_idle_wifi_pref_home = ["Condition:WIFI_GOOD"]
condition_rove_in_idle_wifi_pref_roam = ["Condition:WIFI_GOOD"]
condition_rove_out_idle_wifi_pref_home = ["Condition:WIFI_BAD"]
condition_rove_out_idle_wifi_pref_roam = ["Condition:WIFI_BAD"]
idle_eutran_rsrp = [-108, -115]
idle_geran_rssi = [-90, -100]
idle_ngran_ssrsrp = [-108, -115]
idle_utran_rscp = [-97, -107]
idle_wifi_rssi = [-74, -85]
override_cell_pref_to_ims_pref_home = true
sos_transport_type = 2
video_eutran_rsrp = [-108, -115]
video_geran_rssi = [-90, -100]
video_ngran_ssrsrp = [-108, -115]
video_utran_rscp = [-97, -107]
video_wifi_rssi = [-74, -85]
voice_eutran_rsrp = [-108, -115]
voice_geran_rssi = [-90, -100]
voice_ngran_ssrsrp = [-108, -115]
voice_utran_rscp = [-97, -107]
voice_wifi_rssi = [-74, -85]

[settings.field8]
seconds = 1766559539
