[[carrier_id]]
mcc_mnc = "23420"

[[carrier_id]]
mcc_mnc = "23494"

[[carrier_id]]
mcc_mnc = "23594"

[settings]
version = 77000000001

[[settings.apns.apn]]
name = "3hotspot"
value = "3hotspot"
type = ["dun"]
authtype = 0
protocol = "ipv4v6"
user_visible = false

[[settings.apns.apn]]
name = "3"
value = "three.co.uk"
type = ["default", "mms", "supl", "xcap"]
mmsc = "http://mms.um.three.co.uk:10021/mmsc"
mmsc_proxy = "mms.three.co.uk"
mmsc_proxy_port = "8799"
protocol = "ipv4v6"
mtu = 1440
user_editable = false

[[settings.apns.apn]]
name = "ims"
value = "IMS"
type = ["ims"]
bearer_bitmask = "14|18|20"
protocol = "ipv6"
roaming_protocol = "ipv4v6"
mtu = 1500
user_visible = false

[settings.config]
auto_retry_failed_wifi_emergency_call = true
call_barring_visibility = true
carrier_cross_sim_ims_available = false
carrier_default_wfc_ims_enabled = true
carrier_default_wfc_ims_mode = 1
carrier_supports_ss_over_ut = true
carrier_ussd_method = 2
carrier_volte_available = true
carrier_wfc_ims_available = true
editable_wfc_mode = false
hide_enable_2g = true
hide_enhanced_4g_lte = true
ims_reasoninfo_mapping = ["510|Call completed elsewhere|1014", "*|Call is dropped due to Wi-Fi signal is degraded|1407"]
lte_rsrp_thresholds = [-126, -112, -106, -95]
maxMessageSize = 3145728
non_roaming_operator = ["23410", "23426", "23430", "23431", "23432", "23433", "23434", "23486"]
prefer_2g = false
prefer_3g_visibility = false
show_4g_for_lte_data_icon = true
volte_replacement_rat = 3
wcdma_default_signal_strength_measurement = "rscp"
wfc_operator_error_codes = ["REG09|0"]
wfc_spn_format_idx = 1

[settings.config.ims]
ipv4_sip_mtu_size_cellular = 1300
ipv6_sip_mtu_size_cellular = 1300
phone_context_domain_name = "three.co.uk"
registration_expiry_timer_sec = 3600
request_uri_type = 1
sip_timer_f_millis = 32000

[settings.config.imsss]
network_initiated_ussd_over_ims_supported = false
ut_iptype_home = 0
ut_requires_ims_registration = true
ut_server_based_services = [12, 18, 14, 19, 21, 15, 16, 17, 13, 1, 3, 4, 7, 6, 5, 2, 8, 9, 11]
xcap_over_ut_supported_rats = [6, 3]

[settings.config.imsvoice]
audio_rtp_inactivity_timer_millis = 10000
conference_factory_uri = "Conf-Factory@three.co.uk"
ringing_timer_millis = 60000
session_expires_timer_sec = 250
voice_on_default_bearer_supported = true

[settings.config.imsvoice.audio_codec_capability_payload_types]
amrnb_payload_type = [102]
amrwb_payload_type = [104]
dtmfnb_payload_type = [97]
dtmfwb_payload_type = [96]
evs_payload_type = [127]

[settings.config.imsvoice.evs_payload_description.127]
evs_codec_attribute_bitrate = [0, 6]

[settings.config.iwlan]
child_sa_rekey_hard_timer_sec = 86500
child_sa_rekey_soft_timer_sec = 86400
diffie_hellman_groups = [14, 5]
ike_rekey_hard_timer_in_sec = 86500
ike_rekey_soft_timer_sec = 86400
mcc_mncs = ["234-020"]

[settings.config.qns]
in_call_ho_decision_wlan_to_wwan_without_vops_condition = true
rtp_metrics = [120, 40, 3000, 2000]
xcap_transport_type = 0

[settings.field8]
seconds = 1724979979
