[[carrier_id]]
mcc_mnc = "334140"

[carrier_id.mvno_data]
kind = "spn"
value = "INTEN"

[[settings.apns.apn]]
name = "Inten"
value = "internet.inten.com"
type = ["default"]

[[settings.apns.apn]]
name = "Inten"
value = "ims"
type = ["ims"]

[settings.config]
