[[carrier_id]]
mcc_mnc = "334140"

[carrier_id.mvno_data]
kind = "spn"
value = "IUSATEL"

[[settings.apns.apn]]
name = "Iusacomm"
value = "internet.iusacomm.com"
type = ["default"]

[[settings.apns.apn]]
name = "Iusacomm"
value = "ims"
type = ["ims"]

[settings.config]
