[[carrier_id]]
mcc_mnc = "44020"

[carrier_id.mvno_data]
kind = "gid1"
value = "48FFFF"

[settings]
version = 77000000005

[[settings.apns.apn]]
name = "IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|18|20"
protocol = "ipv6"
roaming_protocol = "ipv6"
user_visible = false

[[settings.apns.apn]]
name = "LINEMO"
value = "plus.acs.jp.v6"
type = ["default", "supl", "hipri", "ia"]
user = "lm"
password = "lm"
authtype = 2
protocol = "ipv4v6"
user_editable = false

[[settings.apns.apn]]
name = "XCAP"
value = "plus.acs.jp"
type = ["xcap"]
user = "lm"
password = "lm"
authtype = 2
protocol = "ipv4v6"
user_visible = false

[settings.config]
_5g_icon_configuration = "connected_mmwave:5G_Plus,connected:5G,connected_rrc_idle:5G,not_restricted_rrc_idle:5G"
_5g_icon_display_grace_period = "connected_mmwave,connected,31;connected_mmwave,legacy,31;connected,legacy,31;connected_mmwave,not_restricted_rrc_con,31;connected,not_restricted_rrc_con,31;not_restricted_rrc_idle,not_restricted_rrc_con,15"
_5g_nr_ssrsrp_thresholds = [-128, -118, -108, -98]
additional_nr_advanced_bands = [77, 78, 79]
allow_hold_call_during_emergency = false
always_show_emergency_alert_onoff = true
call_barring_over_ut_warning = true
call_barring_supports_deactivate_all = false
call_barring_supports_password_change = false
call_barring_visibility = true
call_forwarding_over_ut_warning = true
call_waiting_over_ut_warning = true
caller_id_over_ut_warning = true
carrier_additional_cbs_channels = ["0xA800:type=earthquake, emergency=true", "0xAFEE:type=tsunami, emergency=true", "0xAC00-0xAFED:type=other, emergency=true", "0xA802,0xA804:type=etws_default, emergency=true"]
carrier_certificate = ["8CD14DE82459630273B8D4C4F0C7C042FA0EF419C2B76A0AAD3D7A0646B015B9"]
carrier_default_2g_protection_enabled = true
carrier_force_disable_etws_cmas_test = true
carrier_nr_availabilities = [1, 2]
carrier_roaming_satellite_default_services = [2, 3, 6]
carrier_supports_ss_over_ut = true
carrier_ussd_method = 2
carrier_volte_available = true
default_vm_number = "1416"
default_vm_number_roaming = "+819066514170"
display_hd_plus_icon = false
editable_voicemail_number_setting = false
emergency_call_to_satellite_t911_handover_timeout_millis = 3600000
emergency_messaging_supported = false
enabledMMS = false
gsm_dtmf_tone_delay = 300
hide_enhanced_4g_lte = true
ignore_data_enabled_changed_for_video_calls = true
ims_dtmf_tone_delay = 300
ims_reasoninfo_mapping = ["332||510", "332|q.850|510", "510|Call completed elsewhere|1014"]
is_ims_conference_size_enforced = true
local_disconnect_empty_ims_conference = true
lte_endc_using_user_data_for_rrc_detection = true
maxImageHeight = 1944
maxImageWidth = 2592
maxMessageSize = 307200
min_udp_port_4500_nat_timeout_sec = 120
non_roaming_operator = ["44091", "44092", "44093", "44094"]
nr_advanced_requires_single_cc_above_bandwidth_threshold_bool = true
nr_advanced_threshold_bandwidth_khz = 100000
nr_timers_reset_if_non_endc_and_rrc_idle = true
read_only_apn_types = ["ims"]
recipientLimit = -1
satellite_attach_supported = true
satellite_data_support_mode = 1
satellite_ignore_data_roaming_setting = true
show_4g_for_lte_data_icon = true
show_blocking_pay_phone_option = true
vilte_data_is_metered = false
volte_replacement_rat = 3

[settings.config.bsf]
bsf_server_port = 8088

[settings.config.carrier_supported_satellite_services_per_provider]
44025 = [2, 3, 6]

[settings.config.gps]
es_extension_sec = "300"
lpp_profile = "3"
supl_ver = "0x20002"
use_emergency_pdn_for_emergency_supl = "0"

[settings.config.ims]
ims_user_agent = "#IMEISV#_suppfork"
ipsec_authentication_algorithms = [1]
ipsec_encryption_algorithms = [0]
ipv4_sip_mtu_size_cellular = 1300
ipv6_sip_mtu_size_cellular = 1300
request_uri_type = 1

[settings.config.imsemergency]
cross_stack_redial_timer_sec = 35
emergency_domain_preference = [2]
emergency_domain_preference_roaming = [2, 1]
emergency_over_ims_supported_rats = [3]
emergency_registration_timer_millis = 10000
emergency_requires_volte_enabled = true
quick_cross_stack_redial_timer_sec = 3

[settings.config.imsss]
network_initiated_ussd_over_ims_supported = false
use_csfb_on_xcap_over_ut_failure = false
ut_as_server_port = 443
ut_server_based_services = [20, 12, 18, 14, 19, 21, 15, 16, 17, 13, 1, 3, 4, 7, 6, 5, 2, 0, 8, 9, 11]
ut_terminal_based_services = [10]
ut_transport_type = 3
xcap_over_ut_supported_rats = [6, 3, 5, 1, 2]

[settings.config.imsvoice]
audio_rtcp_inactivity_timer_millis = 10000
audio_rtp_inactivity_timer_millis = 10000
conference_subscribe_type = 0
dedicated_bearer_wait_timer_millis = 4000
mo_call_request_timeout_millis = 10000
ringback_timer_millis = 600000
ringing_timer_millis = 600000
session_privacy_type = 2
session_refresher_type = 0
srvcc_type = []

[settings.config.imsvoice.audio_codec_capability_payload_types]
amrnb_payload_type = [102]
amrwb_payload_type = [104]
dtmfnb_payload_type = [97]
dtmfwb_payload_type = [96]
evs_payload_type = [127, 126]

[settings.config.imsvoice.evs_payload_description.126]
evs_codec_attribute_bandwidth = 1
evs_codec_attribute_bitrate = [0, 6]
evs_codec_attribute_ch_aw_recv = 2

[settings.config.imsvoice.evs_payload_description.127]
evs_codec_attribute_bandwidth = 2
evs_codec_attribute_bitrate = [3, 6]
evs_codec_attribute_ch_aw_recv = 2

[settings.field8]
seconds = 1776868038
