[[carrier_id]]
mcc_mnc = "23208"

[carrier_id.mvno_data]
kind = "spn"
value = "Lycamobile"

[[settings.apns.apn]]
name = "lycamobile"
value = "data.lycamobile.at"
type = ["default", "supl"]
authtype = 1

[settings.config]
