[[carrier_id]]
mcc_mnc = "24223"

[carrier_id.mvno_data]
kind = "spn"
value = "Lycamobile"

[[settings.apns.apn]]
name = "lycamobile"
value = "data.lyca-mobile.no"
type = ["default", "supl"]
authtype = 1

[settings.config]
