[[carrier_id]]
mcc_mnc = "22616"

[carrier_id.mvno_data]
kind = "spn"
value = "Lycamobile"

[[settings.apns.apn]]
name = "lycamobile"
value = "data.lycamobile.ro"
type = ["default", "supl"]
authtype = 1

[settings.config]
