[[carrier_id]]
mcc_mnc = "26804"

[carrier_id.mvno_data]
kind = "spn"
value = "LycaMobile"

[settings]
version = 77000000002

[[settings.apns.apn]]
name = "lycamobile"
value = "data.lycamobile.pt"
type = ["default", "supl"]
authtype = 1

[[settings.apns.apn]]
name = "IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|20"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[settings.config]
carrier_volte_available = true
ignore_rtt_mode_setting = true
rtt_downgrade_supported = true
rtt_supported = true
rtt_supported_while_roaming = true
support_conference_call = false

[settings.field8]
seconds = 1736946312
