[[carrier_id]]
mcc_mnc = "23430"

[carrier_id.mvno_data]
kind = "spn"
value = "LycaMobile"

[settings]
version = 77000000001

[[settings.apns.apn]]
name = "Lycamobile"
value = "data.lycamobile.co.uk"
type = ["default", "supl"]
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|20"
protocol = "ipv6"
roaming_protocol = "ipv4v6"
user_visible = false

[settings.config]
carrier_volte_available = true
non_roaming_operator = ["23410", "23420", "23430", "23431", "23432", "23433", "23434", "23486"]
show_4g_for_lte_data_icon = true

[settings.field8]
seconds = 1732242357
