[[carrier_id]]
mcc_mnc = "52503"

[settings]
version = 77000000012

[[settings.apns.apn]]
name = "Sunsurf Mobile"
value = "sunsurf"
type = ["default", "supl"]
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "M1 IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|18|20"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[[settings.apns.apn]]
name = "M1 XCAP"
value = "xcap"
type = ["xcap"]
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[settings.config]
_5g_nr_ssrsrp_thresholds = [-128, -118, -108, -98]
carrier_default_2g_protection_enabled = true
carrier_default_wfc_ims_mode = 1
carrier_nr_availabilities = [1, 2]
carrier_supports_ss_over_ut = true
carrier_ussd_method = 1
carrier_volte_available = true
carrier_wfc_ims_available = true
hide_enhanced_4g_lte = true
iwlan_handover_policy = ["source=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN|UNKNOWN, target=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN, type=disallowed, capabilities=EIMS|MMS|XCAP|CBS", "source=IWLAN|UNKNOWN, target=GERAN|UTRAN, type=disallowed, capabilities=IMS", "source=GERAN|UTRAN, target=IWLAN, type=disallowed, capabilities=IMS", "source=NGRAN|IWLAN, target=NGRAN|IWLAN, incall=true, type=disallowed, capabilities=IMS", "source=EUTRAN|NGRAN|IWLAN, target=EUTRAN|NGRAN|IWLAN, type=allowed, capabilities=IMS"]
show_4g_for_lte_data_icon = true
support_ims_conference_event_package = false
wfc_spn_format_idx = 1

[settings.config.bsf]
bsf_server_port = 8090

[settings.config.imsemergency]
emergency_domain_preference = [2, 1]
emergency_domain_preference_roaming = [2, 1]
emergency_over_ims_supported_rats = [3]

[settings.config.imsss]
ut_as_server_port = 8090
ut_requires_ims_registration = true
xcap_over_ut_supported_rats = [6, 3, 1, 2]

[settings.config.imsvoice.audio_codec_capability_payload_types]
amrnb_payload_type = [98, 103]
amrwb_payload_type = [100, 105]
dtmfnb_payload_type = [97]
dtmfwb_payload_type = [96]

[settings.config.iwlan]
epdg_address_priority = [0]
epdg_static_address = "epdg.mobileone.net.sg"
update_n1_mode_on_ui_change = true

[settings.config.qns]
xcap_transport_type = 0

[settings.field8]
seconds = 1773236747
