[[carrier_id]]
mcc_mnc = "42003"

[settings]
version = 77000000001

[[settings.apns.apn]]
name = "Mobily WEB"
value = "web1"
type = ["default", "supl"]

[[settings.apns.apn]]
name = "Mobily prepaid - GPRS"
value = "wap2"
type = ["default", "supl"]
proxy = "10.3.2.133"
port = "8080"

[[settings.apns.apn]]
name = "Mobily postpaid - GPRS"
value = "wap1"
type = ["default", "supl"]
proxy = "10.3.2.133"
port = "8080"

[[settings.apns.apn]]
name = "Mobily WEB 2"
value = "web2"
type = ["default", "supl"]

[[settings.apns.apn]]
name = "Mobily MMS Postpaid"
value = "mms1"
type = ["mms"]
mmsc = "http://10.3.3.133:9090/was"
mmsc_proxy = "10.3.2.133"
mmsc_proxy_port = "8080"

[[settings.apns.apn]]
name = "Mobily MMS Prepaid"
value = "mms2"
type = ["mms"]
mmsc = "http://10.3.3.133:9090/was"
mmsc_proxy = "10.3.2.133"
mmsc_proxy_port = "8080"

[[settings.apns.apn]]
name = "IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|18|20"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[settings.config]
carrier_volte_available = true
carrier_wfc_ims_available = true
wfc_spn_format_idx = 1

[settings.config.imsemergency]
emergency_domain_preference = [2, 1]
emergency_domain_preference_roaming = [2, 1]
emergency_over_ims_supported_rats = [3]

[settings.config.imsss]
xcap_over_ut_supported_rats = []

[settings.config.imsvoice.audio_codec_capability_payload_types]
amrnb_payload_type = [98, 103]
amrwb_payload_type = [100, 105]
dtmfnb_payload_type = [97]
dtmfwb_payload_type = [96]

[settings.config.iwlan]
epdg_address_priority = [0]
epdg_static_address = "epdg.mobily.com.sa"

[settings.config.qns]
support_wfc_during_airplane_mode = false

[settings.field8]
seconds = 1724979979
