[[carrier_id]]
mcc_mnc = "27411"

[settings]
version = 77000000001

[[settings.apns.apn]]
name = "MMS Nova"
value = "mms.nova.is"
type = ["mms"]
mmsc = "http://mmsc.nova.is"
mmsc_proxy = "10.10.2.60"
mmsc_proxy_port = "8080"

[[settings.apns.apn]]
name = "Net Nova"
value = "net.nova.is"
type = ["default", "supl", "xcap"]
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|18|20"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[settings.config]
carrier_default_wfc_ims_roaming_enabled = true
carrier_supports_ss_over_ut = true
carrier_volte_available = true
carrier_wfc_ims_available = true
hide_enhanced_4g_lte = true
iwlan_handover_policy = ["source=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN|UNKNOWN, target=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN, type=disallowed, capabilities=EIMS|MMS|XCAP|CBS", "source=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN|UNKNOWN, target=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN, roaming=true, type=disallowed, capabilities=IMS", "source=IWLAN|UNKNOWN, target=GERAN|UTRAN, type=disallowed, capabilities=IMS", "source=GERAN|UTRAN, target=IWLAN, type=disallowed, capabilities=IMS", "source=EUTRAN|NGRAN|IWLAN, target=EUTRAN|NGRAN|IWLAN, type=allowed, capabilities=IMS"]
wfc_spn_format_idx = 1

[settings.config.imsemergency]
emergency_over_ims_supported_rats = [3]

[settings.config.imsss]
xcap_over_ut_supported_rats = [5, 6, 3, 1, 2]

[settings.config.imsvoice.evs_payload_description.127]
evs_codec_attribute_bitrate = [0, 6]
evs_codec_attribute_dtx = false
evs_codec_attribute_dtx_recv = false
evs_codec_attribute_hf_only = 1

[settings.field8]
seconds = 1724979979
