[[carrier_id]]
mcc_mnc = "23410"

[settings]
version = 77000000008

[[settings.apns.apn]]
name = "O2 Pay Monthly"
value = "mobile.o2.co.uk"
type = ["default", "dun", "mms", "supl", "hipri", "xcap"]
user = "o2"
password = "p"
authtype = 1
mmsc = "http://mmsc.mms.o2.co.uk:8002"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_editable = false

[[settings.apns.apn]]
name = "O2 IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|18|20"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[settings.config]
auto_retry_failed_wifi_emergency_call = true
carrier_default_wfc_ims_enabled = true
carrier_nr_availabilities = [1, 2]
carrier_roaming_satellite_default_services = [2, 3, 6]
carrier_supports_ss_over_ut = true
carrier_ussd_method = 2
carrier_volte_available = true
carrier_wfc_ims_available = true
default_vm_number = "901"
disable_supplementary_services_in_airplane_mode = true
display_hd_audio_property = false
emergency_messaging_supported = true
hide_lte_plus_data_icon = false
ims_reasoninfo_mapping = ["510|Call completed elsewhere|1014", "*|Call is dropped due to Wi-Fi signal is degraded|1407"]
non_roaming_operator = ["23420", "23426", "23430", "23431", "23432", "23433", "23434", "23486"]
prefer_2g = false
radio_restart_failure_causes = [55]
read_only_apn_types = []
satellite_attach_supported = true
satellite_data_support_mode = 1
satellite_entitlement_supported = true
satellite_ignore_data_roaming_setting = true
show_4g_for_lte_data_icon = true
smsToMmsTextThreshold = 10
vonr_enabled = true
wfc_spn_format_idx = 1

[settings.config.bsf]
bsf_server_port = 443
bsf_transport_type = 3

[settings.config.carrier_supported_satellite_services_per_provider]
23402 = [2, 3, 6]

[settings.config.ims]
ipv4_sip_mtu_size_cellular = 1280
ipv6_sip_mtu_size_cellular = 1280
sip_timer_b_millis = 90000
sip_timer_f_millis = 32000
sip_timer_j_millis = 32000

[settings.config.imsemergency]
prefer_ims_emergency_when_voice_calls_on_cs = true

[settings.config.imsserviceentitlement]
entitlement_server_url = "https://ses.o2.co.uk:10024"

[settings.config.imsss]
network_initiated_ussd_over_ims_supported = false
ut_as_server_port = 443
ut_iptype_home = 0
ut_transport_type = 3
xcap_over_ut_supported_rats = [6, 3, 1, 2]

[settings.config.imsvoice]
conference_subscribe_type = 0
dedicated_bearer_wait_timer_millis = 10000
minimum_session_expires_timer_sec = 600
oip_source_from_header = true
prack_supported_for_18x = true

[settings.config.imsvoice.audio_codec_capability_payload_types]
amrnb_payload_type = [102]
amrwb_payload_type = [104]
dtmfnb_payload_type = [97]
dtmfwb_payload_type = [96]
evs_payload_type = [126]

[settings.config.imsvoice.evs_payload_description.126]
evs_codec_attribute_bitrate = [0, 6]
evs_codec_attribute_ch_aw_recv = 3

[settings.config.iwlan]
child_sa_rekey_hard_timer_sec = 43300
child_sa_rekey_soft_timer_sec = 43200
diffie_hellman_groups = [14]
dpd_timer_sec = 1800
ike_rekey_hard_timer_in_sec = 43300
ike_rekey_soft_timer_sec = 43200
ike_remote_id_type = 11
supported_ike_session_encryption_algorithms = [12, 13]

[settings.config.qns]
support_wfc_in_international_roaming = false
xcap_transport_type = 0

[settings.field8]
seconds = 1768403337
