[[carrier_id]]
mcc_mnc = "27099"

[settings]
version = 77000000001

[[settings.apns.apn]]
name = "Orange"
value = "orange.lu"
type = ["default", "mms", "supl"]
mmsc = "http://mms.orange.lu"
mmsc_proxy = "212.88.139.44"
mmsc_proxy_port = "8080"

[[settings.apns.apn]]
name = "IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|18|20"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[settings.config]
carrier_default_wfc_ims_roaming_enabled = true
carrier_volte_available = true
carrier_wfc_ims_available = true
wfc_spn_format_idx = 1

[settings.config.imsemergency]
emergency_domain_preference = [2, 1]
emergency_domain_preference_roaming = [2, 1]
emergency_over_ims_supported_rats = [3]
emergency_scan_timer_sec = 5

[settings.config.imsss]
ut_server_based_services = []
ut_terminal_based_services = [10]
xcap_over_ut_supported_rats = []

[settings.config.imsvoice.audio_codec_capability_payload_types]
amrnb_payload_type = [98, 103]
amrwb_payload_type = [100, 105]
dtmfnb_payload_type = [97]
dtmfwb_payload_type = [96]
evs_payload_type = [127, 126]

[settings.config.imsvoice.evs_payload_description.126]
evs_codec_attribute_bitrate = [0, 6]

[settings.config.imsvoice.evs_payload_description.127]
evs_codec_attribute_bandwidth = 2
evs_codec_attribute_bitrate = [3, 6]

[settings.field8]
seconds = 1724979979
