[[carrier_id]]
mcc_mnc = "27001"

[settings]
version = 77000000002

[[settings.apns.apn]]
name = "POST Internet"
value = "web.pt.lu"
type = ["default", "ia", "supl"]

[[settings.apns.apn]]
name = "IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|18|20"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[[settings.apns.apn]]
name = "POST XCAP"
value = "hos"
type = ["xcap"]
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[settings.config]
carrier_default_wfc_ims_mode = 1
carrier_supports_ss_over_ut = true
carrier_volte_available = true
carrier_wfc_ims_available = true
display_hd_plus_icon = true
enabledMMS = false
wfc_spn_format_idx = 1

[settings.config.bsf]
bsf_server_fqdn = "bsf.mnc001.mcc270.pub.3gppnetwork.org"
bsf_server_port = 10080

[settings.config.imsemergency]
emergency_domain_preference = [2, 1]
emergency_domain_preference_roaming = [2, 1]
emergency_over_ims_supported_rats = [3]

[settings.config.imsss]
ut_as_server_fqdn = "xcap.ims.mnc001.mcc270.pub.3gppnetwork.org"
ut_server_based_services = [20, 12, 18, 14, 19, 21, 15, 16, 17, 13, 1, 3, 4, 7, 6, 5, 2, 0, 8, 9, 11]
ut_terminal_based_services = [10]
xcap_over_ut_supported_rats = [6, 3, 5, 1, 2]

[settings.config.imsvoice.evs_payload_description.127]
evs_codec_attribute_bitrate = [4, 6]

[settings.field8]
seconds = 1729074853
