[[carrier_id]]
mcc_mnc = "47002"

[settings]
version = 77000000002

[[settings.apns.apn]]
name = "Internet"
value = "internet"
type = ["default"]
bearer_bitmask = "14|20"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|20"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[settings.config]
carrier_volte_available = true
enhanced_4g_lte_on_by_default = false

[settings.field8]
seconds = 1763550047
