[[carrier_id]]
mcc_mnc = "310120"

[carrier_id.mvno_data]
kind = "gid1"
value = "000004"

[[carrier_id]]
mcc_mnc = "312530"

[carrier_id.mvno_data]
kind = "gid1"
value = "000004"

[settings]
version = 77000000001

[[settings.apns.apn]]
name = "Internet"
value = "sprint"
type = ["cbs", "default", "supl"]
bearer_bitmask = "4|5|6|7|8|12"

[[settings.apns.apn]]
name = "Internet"
value = "sprint"
type = ["default", "supl", "dun", "cbs"]
bearer_bitmask = "4|5|6|7|8|12"
profile_id = 1
modem_cognitive = true
user_editable = false

[[settings.apns.apn]]
name = "OTA"
value = "otasn"
type = ["ia", "fota"]
user = "null"
password = "null"
protocol = "ipv4v6"

[[settings.apns.apn]]
name = "MMS"
value = "mms"
type = ["mms"]
mmsc = "http://mmsc.vmobl.com:8088"
mmsc_proxy = "oap7.sprintpcs.com"
mmsc_proxy_port = "80"

[settings.config]
allow_non_emergency_calls_in_ecm = false
apn_expand = false
carrier_default_wfc_ims_mode = 1
carrier_default_wfc_ims_roaming_mode = 1
carrier_eri_file_name = "eri.xml"
carrier_settings_activity_component_name = "com.android.sdm.plugins.sprintdm/.SprintCarrierSettingsActivity"
carrier_settings_enable = true
cdma_3waycall_flash_delay = 0
config_telephony_use_own_number_for_voicemail = true
dtmf_type_enabled = true
emailGatewayNumber = "6245"
emergency_number_prefix = ["*272"]
enableSMSDeliveryReports = false
enable_apps = ["com.android.omadm.service", "com.android.sdm.plugins.sprintdm"]
httpParams = "X-MDN: ##LINE1##|Proxy-Authorization: Basic ##NAI##"
maxImageHeight = 1944
maxImageWidth = 2592
maxMessageSize = 2097152
maxSubjectLength = 80
mmi_two_digit_number_pattern = ["*2"]
naiSuffix = ":pcs"
recipientLimit = 40
show_cdma_choices = false
smsToMmsTextThreshold = 6
stk_disable_launch_browser = true
supportMmsContentDisposition = false
support_swap_after_merge = true
use_hfa_for_provisioning = true
voicemail_notification_persistent = true
volte_replacement_rat = 6
wfc_emergency_address_carrier_app = "com.google.android.wfcactivation/.WfcActivationActivity"
wfc_spn_format_idx = 1

[settings.config.ims]
ims_user_agent = "#MANUFACTURE# #MODEL# #BUILD#"

[settings.config.imsemergency]
emergency_domain_preference = [2, 1]
emergency_domain_preference_roaming = [2, 1]
emergency_over_ims_supported_rats = [3]

[settings.config.imsss]
xcap_over_ut_supported_rats = []

[settings.config.imsvoice]
include_caller_id_service_codes_in_sip_invite = true

[settings.config.imsvoice.audio_codec_capability_payload_types]
amrnb_payload_type = [98, 103]
amrwb_payload_type = [100, 105]
dtmfnb_payload_type = [97]
dtmfwb_payload_type = [96]

[settings.config.imswfc]
emergency_call_over_emergency_pdn = true

[settings.field8]
seconds = 1724979979
