[[carrier_id]]
mcc_mnc = "23440"

[[carrier_id]]
mcc_mnc = "24007"

[carrier_id.mvno_data]
kind = "gid1"
value = "48"

[settings]
version = 77000000006

[[settings.apns.apn]]
name = "spusu"
value = "web"
type = ["default", "supl"]
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "ims"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|18|20"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[settings.config]
carrier_default_wfc_ims_enabled = true
carrier_default_wfc_ims_mode = 1
carrier_volte_available = true
carrier_wfc_ims_available = true
wfc_spn_format_idx = 1

[settings.config.ims]
request_uri_type = 1
sip_over_ipsec_enabled = false
sip_preferred_transport = 0

[settings.config.iwlan]
epdg_address_priority = [0]
epdg_static_address = "epdg.epc.mnc040.mcc234.pub.3gppnetwork.org"

[settings.field8]
seconds = 1773236747
