[[carrier_id]]
mcc_mnc = "29364"

[settings]
version = 77000000003

[[settings.apns.apn]]
name = "T2"
value = "internet.t-2.net"
type = ["default", "mms", "supl"]
mmsc = "http://www.mms.t-2.net:8002"
mmsc_proxy = "172.20.18.137"
mmsc_proxy_port = "8080"

[[settings.apns.apn]]
name = "IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|18|20"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[settings.config]
carrier_default_wfc_ims_enabled = true
carrier_volte_available = true
carrier_wfc_ims_available = true
ignore_rtt_mode_setting = true
rtt_downgrade_supported = true
rtt_supported = true
rtt_supported_while_roaming = true
wfc_spn_format_idx = 1

[settings.config.imsemergency]
emergency_domain_preference = [2, 1]
emergency_domain_preference_roaming = [2, 1]
emergency_over_ims_supported_rats = [3]

[settings.config.iwlan]
diffie_hellman_groups = [5, 14]

[settings.field8]
seconds = 1761862567
