[[carrier_id]]
mcc_mnc = "23427"

[settings]
version = 77000000002

[[settings.apns.apn]]
name = "TCL MOVE"
value = "move.dataxs.mobi"
type = ["default", "dun"]
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|20"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[settings.config]
read_only_apn_types = []

[settings.config.imsvoice]
prack_supported_for_18x = true

[settings.config.imsvoice.audio_codec_capability_payload_types]
amrnb_payload_type = [98, 103]
amrwb_payload_type = [100, 105]
dtmfnb_payload_type = [97]
dtmfwb_payload_type = [96]

[settings.field8]
seconds = 1769617073
