[[carrier_id]]
mcc_mnc = "24007"

[settings]
version = 77000000004

[[settings.apns.apn]]
name = "Tele2 Internet"
value = "internet.tele2.se"
type = ["default", "supl", "mms"]
mmsc = "http://mmsc.tele2.se/"
mmsc_proxy = "mmsproxy.tele2.se"
mmsc_proxy_port = "8080"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "ims"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|18|20"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false
field27 = "1|2|3|8|9|10|13|14|15|18|20"

[[settings.apns.apn]]
name = "Tele2 Emergency"
value = "EMERGENCY"
type = ["emergency"]
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[[settings.apns.apn]]
name = "xcap"
value = "hos"
type = ["xcap"]
bearer_bitmask = "14|18|20"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[settings.config]
call_barring_visibility = true
carrier_default_wfc_ims_enabled = true
carrier_default_wfc_ims_mode = 1
carrier_supports_ss_over_ut = true
carrier_ussd_method = 1
carrier_volte_available = true
carrier_wfc_ims_available = true
ignore_rtt_mode_setting = true
is_ims_conference_size_enforced = true
prefer_3g_visibility = false
rtt_downgrade_supported = true
rtt_supported = true
rtt_supported_while_roaming = true
show_4g_for_lte_data_icon = true
wfc_spn_format_idx = 1

[settings.config.ims]
ipv4_sip_mtu_size_cellular = 1230
ipv6_sip_mtu_size_cellular = 1280
request_uri_type = 1
sip_timer_f_millis = 32000

[settings.config.imsss]
ut_requires_ims_registration = true
ut_server_based_services = [12, 18, 14, 19, 21, 15, 16, 17, 13, 1, 3, 4, 7, 6, 5, 2, 0, 8, 9, 11]
ut_terminal_based_services = [10]
xcap_over_ut_supported_rats = [6, 3, 5]

[settings.config.imsvoice]
minimum_session_expires_timer_sec = 1800

[settings.config.imsvoice.audio_codec_capability_payload_types]
amrnb_payload_type = [102]
amrwb_payload_type = [104]
dtmfnb_payload_type = [97]
dtmfwb_payload_type = [96]
evs_payload_type = [127]

[settings.config.imsvoice.evs_payload_description.127]
evs_codec_attribute_bitrate = [3, 6]
evs_codec_attribute_ch_aw_recv = 255

[settings.config.imswfc]
emergency_call_over_emergency_pdn = true

[settings.config.iwlan]
child_sa_rekey_hard_timer_sec = 7200
child_sa_rekey_soft_timer_sec = 7140
child_session_aes_cbc_key_size = [256]
diffie_hellman_groups = [14, 5, 2]
ike_rekey_hard_timer_in_sec = 86400
ike_rekey_soft_timer_sec = 86340
ike_remote_id_type = 11
ike_session_encryption_aes_cbc_key_size = [256]
supported_child_session_encryption_algorithms = [12]
supported_ike_session_encryption_algorithms = [12]
supported_integrity_algorithms = [2, 5]

[settings.config.qns]
sos_transport_type = 2

[settings.field8]
seconds = 1771422511
