[[carrier_id]]
mcc_mnc = "29401"

[settings]
version = 77000000006

[[settings.apns.apn]]
name = "Internet"
value = "internet"
type = ["default", "supl"]
user = "internet"
password = "t-mobile"
authtype = 1
protocol = "ipv4v6"

[[settings.apns.apn]]
name = "MMS"
value = "mms"
type = ["mms"]
user = "mms"
password = "mms"
authtype = 1
mmsc = "http://mms.t-mobile.com.mk"
mmsc_proxy = "62.162.155.227"
mmsc_proxy_port = "8080"

[[settings.apns.apn]]
name = "IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|20"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[[settings.apns.apn]]
name = "Telekom XCAP"
value = "hos"
type = ["xcap"]
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[settings.config]
carrier_supports_ss_over_ut = true
carrier_volte_available = true
default_vm_number = "+38970121212"
display_hd_audio_property = false
hide_enhanced_4g_lte = true
maxImageHeight = 1944
maxImageWidth = 2592
maxMessageSize = 102400
show_4g_for_lte_data_icon = true

[settings.config.ims]
ims_user_agent = "#MANUFACTURE# - #MODEL# - #BUILD#"
keep_pdn_up_in_no_vops = true

[settings.config.imsemergency]
emergency_over_ims_supported_rats = [3]
emergency_registration_timer_millis = 5000

[settings.config.imssms]
sms_over_ims_supported_rats = [3, 6]

[settings.config.imsss]
ut_iptype_roaming = 0
xcap_over_ut_supported_rats = [6, 3, 1, 2]

[settings.config.imsvoice]
mo_call_request_timeout_millis = 0

[settings.config.imsvoice.audio_codec_capability_payload_types]
amrnb_payload_type = [98, 103]
amrwb_payload_type = [100, 105]
dtmfnb_payload_type = [97]
dtmfwb_payload_type = [96]

[settings.field8]
seconds = 1756276532
