[[carrier_id]]
mcc_mnc = "24803"

[settings]
version = 77000000005

[[settings.apns.apn]]
name = "Tele2 Internet"
value = "internet.tele2.ee"
type = ["default", "supl", "mms"]
mmsc = "http://mmsc.tele2.ee"
mmsc_proxy = "mmsproxy.tele2.ee"
mmsc_proxy_port = "8080"

[[settings.apns.apn]]
name = "IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|18|20"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[[settings.apns.apn]]
name = "xcap"
value = "hos"
type = ["xcap"]
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[settings.config]
carrier_default_wfc_ims_enabled = true
carrier_default_wfc_ims_mode = 1
carrier_supports_ss_over_ut = true
carrier_volte_available = true
carrier_wfc_ims_available = true
ignore_rtt_mode_setting = true
rtt_downgrade_supported = true
rtt_supported = true
rtt_supported_while_roaming = true
wfc_spn_format_idx = 1

[settings.config.bsf]
bsf_server_fqdn = "bsf.ims.mnc003.mcc248.pub.3gppnetwork.org"
bsf_server_port = 8081

[settings.config.imsemergency]
emergency_domain_preference = [2, 1]
emergency_domain_preference_roaming = [2, 1]
emergency_over_ims_supported_rats = [3]

[settings.config.imsss]
ut_as_server_fqdn = "xcap.ims.mnc003.mcc248.pub.3gppnetwork.org"
ut_requires_ims_registration = true
xcap_over_ut_supported_rats = [6, 3, 5, 1, 2]

[settings.config.imsvoice.audio_codec_capability_payload_types]
amrnb_payload_type = [98, 103]
amrwb_payload_type = [100, 105]
dtmfnb_payload_type = [97]
dtmfwb_payload_type = [96]

[settings.config.iwlan]
child_sa_rekey_hard_timer_sec = 1500
child_sa_rekey_soft_timer_sec = 1400
diffie_hellman_groups = [14]
ike_device_identity_supported = true
ike_rekey_hard_timer_in_sec = 3000
ike_rekey_soft_timer_sec = 2900

[settings.config.qns]
idle_eutran_rsrp = [-115, -118]
voice_eutran_rsrp = [-115, -118]

[settings.field8]
seconds = 1736946312
