[[carrier_id]]
mcc_mnc = "26002"

[settings]
version = 77000000011

[[settings.apns.apn]]
name = "Internet"
value = "internet"
type = ["default", "ia", "supl"]
authtype = 1
protocol = "ipv4v6"

[[settings.apns.apn]]
name = "HOS"
value = "hos"
type = ["mms", "xcap"]
authtype = 1
mmsc = "http://mms/servlets/mms"
mmsc_proxy = "213.158.194.226"
mmsc_proxy_port = "8080"
protocol = "ipv4v6"
user_visible = false

[[settings.apns.apn]]
name = "IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|18|20"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[settings.config]
carrier_default_data_roaming_enabled = true
carrier_default_wfc_ims_enabled = true
carrier_default_wfc_ims_mode = 1
carrier_default_wfc_ims_roaming_enabled = true
carrier_default_wfc_ims_roaming_mode = 1
carrier_supports_ss_over_ut = true
carrier_ussd_method = 1
carrier_volte_available = true
carrier_wfc_ims_available = true
default_vm_number = "+48602950000"
display_hd_audio_property = false
hide_enhanced_4g_lte = true
ignore_rtt_mode_setting = true
iwlan_handover_policy = ["source=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN|UNKNOWN, target=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN, type=disallowed, capabilities=EIMS|MMS|XCAP|CBS", "source=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN|UNKNOWN, target=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN, roaming=true, type=disallowed, capabilities=IMS", "source=IWLAN|UNKNOWN, target=GERAN|UTRAN, type=disallowed, capabilities=IMS", "source=GERAN|UTRAN, target=IWLAN, type=disallowed, capabilities=IMS", "source=EUTRAN|NGRAN|IWLAN, target=EUTRAN|NGRAN|IWLAN, type=allowed, capabilities=IMS"]
prefer_3g_visibility = false
rtt_downgrade_supported = true
rtt_supported = true
rtt_supported_while_roaming = true
wfc_spn_format_idx = 4

[settings.config.ims]
ims_user_agent = "#MANUFACTURE# - #MODEL# - #BUILD#"
keep_pdn_up_in_no_vops = true

[settings.config.imsemergency]
emergency_registration_timer_millis = 5000

[settings.config.imsss]
ut_iptype_roaming = 0
ut_server_based_services = [20, 12, 18, 14, 19, 21, 15, 16, 17, 13, 1, 3, 4, 7, 6, 5, 2, 0, 8, 9, 11]
ut_terminal_based_services = [10]
xcap_over_ut_supported_rats = [5, 6, 3, 1, 2]

[settings.config.imsvoice]
mo_call_request_timeout_millis = 0

[settings.config.imsvoice.audio_codec_capability_payload_types]
amrnb_payload_type = [98, 103]
amrwb_payload_type = [100, 105]
dtmfnb_payload_type = [97]
dtmfwb_payload_type = [96]
evs_payload_type = [126]

[settings.config.imsvoice.evs_payload_description.126]
evs_codec_attribute_bitrate = [0, 6]

[settings.config.iwlan]
add_ke_to_child_session_rekey = true
diffie_hellman_groups = [14, 5, 2]

[settings.config.qns]
condition_rove_in_idle_wifi_pref_home = ["Condition:WIFI_GOOD"]
condition_rove_in_idle_wifi_pref_roam = ["Condition:WIFI_GOOD"]
condition_rove_out_idle_wifi_pref_home = ["Condition:WIFI_BAD"]
condition_rove_out_idle_wifi_pref_roam = ["Condition:WIFI_BAD"]
idle_geran_rssi = [-89, -106]
idle_utran_rscp = [-99, -103]
mms_rat_preference = 2
override_cell_pref_to_ims_pref_home = true
support_wfc_recovery = false
voice_geran_rssi = [-89, -102]
voice_utran_rscp = [-89, -105]
xcap_rat_preference = 2

[settings.field8]
seconds = 1765981876
