[[carrier_id]]
mcc_mnc = "311210"

[[carrier_id]]
mcc_mnc = "313260"

[carrier_id.mvno_data]
kind = "imsi"
value = "31326010200"

[settings]
version = 77000000002

[[settings.apns.apn]]
name = "Farmers GPRS"
value = "internet.farmerswireless.com"
type = ["default", "supl"]

[[settings.apns.apn]]
name = "Farmers MMS"
value = "mms.farmers.com"
type = ["mms"]
mmsc = "http://172.16.0.37:8514"

[[settings.apns.apn]]
name = "IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|20"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[settings.config.imsvoice]
carrier_volte_roaming_available = false
oip_source_from_header = true
prack_supported_for_18x = true

[settings.config.imsvoice.amrnb_payload_description.103]
amr_codec_attribute_modeset = [0, 2, 4, 7]
amr_codec_attribute_payload_format = 1

[settings.config.imsvoice.amrnb_payload_description.98]
amr_codec_attribute_modeset = [0, 2, 4, 7]

[settings.config.imsvoice.audio_codec_capability_payload_types]
amrnb_payload_type = [98, 103]
amrwb_payload_type = [100, 105]
dtmfnb_payload_type = [97]
dtmfwb_payload_type = [96]

[settings.field8]
seconds = 1769617073
