[[carrier_id]]
mcc_mnc = "72402"

[[carrier_id]]
mcc_mnc = "72403"

[[carrier_id]]
mcc_mnc = "72404"

[settings]
version = 77000000002

[[settings.apns.apn]]
name = "TIM Connect"
value = "timbrasil.br"
type = ["default", "mms", "supl"]
user = "tim"
password = "tim"
authtype = 1
mmsc = "http://mms.tim.br"
mmsc_proxy = "189.40.191.96"
mmsc_proxy_port = "8080"
protocol = "ipv4v6"

[[settings.apns.apn]]
name = "IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|20"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[[settings.apns.apn]]
name = "TIM xcap"
value = "timbrasil.br"
type = ["xcap"]
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[settings.config]
carrier_supports_ss_over_ut = true
carrier_volte_available = true
show_4g_for_lte_data_icon = true

[settings.config.bsf]
bsf_server_fqdn = "bsf.ims.mnc002.mcc724.pub.3gppnetwork.org"

[settings.config.ims]
sip_over_ipsec_enabled = false

[settings.config.imsss]
ut_as_server_fqdn = "xcap.ims.mnc002.mcc724.pub.3gppnetwork.org"
ut_server_based_services = [0, 1, 2, 3, 4, 5, 6, 7, 12, 17, 18, 19, 20, 21, 13, 14, 15, 16, 8, 11, 9]
ut_terminal_based_services = [10]

[settings.field8]
seconds = 1733386101
