[[carrier_id]]
mcc_mnc = "310026"

[[carrier_id]]
mcc_mnc = "310160"

[[carrier_id]]
mcc_mnc = "310200"

[[carrier_id]]
mcc_mnc = "310210"

[[carrier_id]]
mcc_mnc = "310220"

[[carrier_id]]
mcc_mnc = "310230"

[[carrier_id]]
mcc_mnc = "310240"

[[carrier_id]]
mcc_mnc = "310250"

[[carrier_id]]
mcc_mnc = "310260"

[[carrier_id]]
mcc_mnc = "310270"

[[carrier_id]]
mcc_mnc = "310300"

[[carrier_id]]
mcc_mnc = "310310"

[[carrier_id]]
mcc_mnc = "310490"

[[carrier_id]]
mcc_mnc = "310530"

[[carrier_id]]
mcc_mnc = "310640"

[[carrier_id]]
mcc_mnc = "310660"

[[carrier_id]]
mcc_mnc = "310800"

[[carrier_id]]
mcc_mnc = "311490"

[[carrier_id]]
mcc_mnc = "311882"

[[carrier_id]]
mcc_mnc = "312250"

[settings]
version = 77000000013

[[settings.apns.apn]]
name = "T-Mobile Tethering"
value = "pcweb.tmobile.com"
type = ["dun"]
protocol = "ipv6"
user_visible = false
field30 = 1

[[settings.apns.apn]]
name = "T-Mobile US"
value = "fast.t-mobile.com"
type = ["default", "supl", "ia", "mms", "xcap"]
bearer_bitmask = "1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|17|20"
mmsc = "http://mms.msg.eng.t-mobile.com/mms/wapenc"
protocol = "ipv6"
mtu = 1440
user_editable = false

[[settings.apns.apn]]
name = "T-Mobile US IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|18|20"
protocol = "ipv6"
roaming_protocol = "ipv4v6"
mtu = 1440
user_visible = false
field28 = 1

[[settings.apns.apn]]
name = "T-Mobile MMS"
value = "TMUS"
type = ["mms", "xcap"]
bearer_bitmask = "18"
mmsc = "http://mms.msg.eng.t-mobile.com/mms/wapenc"
protocol = "ipv6"
roaming_protocol = "ipv6"
user_visible = false

[[settings.apns.apn]]
name = "T-Mobile Emergency"
value = "sos"
type = ["emergency"]
protocol = "ipv6"
roaming_protocol = "ipv4v6"
user_visible = false
field28 = 1

[settings.config]
_5g_icon_configuration = "connected_mmwave:5G_Plus,connected:5G,not_restricted_rrc_idle:5G,not_restricted_rrc_con:5G"
_5g_icon_display_grace_period = "connected_mmwave,legacy,30;connected_mmwave,connected,30;connected_mmwave,not_restricted_rrc_idle,30;connected_mmwave,not_restricted_rrc_con,30;connected,legacy,30;not_restricted_rrc_idle,legacy,30;not_restricted_rrc_con,legacy,30"
_5g_nr_ssrsrp_thresholds = [-120, -114, -109, -100]
additional_nr_advanced_bands = [25, 41, 48, 66, 71, 77, 258, 260, 261]
allow_metered_network_for_cert_download = true
call_composer_picture_server_url = "ue.fcs.mstore.msg.t-mobile.com"
carrier_certificate = ["27F96DBAB77B31F6953E4CD2C2DEFE15F5D7C78F073DD7162018EF476B097C34", "3D1A4BEF6EE7AF7D34D120E7B1AAC0DD245585DE6237CF100F68333AFACFF562", "92B5F8117FBD9BD5738FF168A4FA12CBE284BE834EDE1A7BB44DD8455BA15920"]
carrier_default_data_roaming_enabled = true
carrier_default_wfc_ims_enabled = true
carrier_default_wfc_ims_mode = 1
carrier_default_wfc_ims_roaming_enabled = true
carrier_default_wfc_ims_roaming_mode = 2
carrier_ims_gba_required = true
carrier_nr_availabilities = [1, 2]
carrier_roaming_satellite_default_services = [2, 3, 6]
carrier_roaming_satellite_emergency_messaging_redirection_destination = "911"
carrier_supports_ss_over_ut = true
carrier_ussd_method = 1
carrier_volte_available = true
carrier_vowifi_tty_supported = false
carrier_vt_available = true
carrier_wfc_ims_available = true
config_ims_rcs_package_override = ""
data_connected_roaming_notification_excluded_mccs = ["310", "311", "312", "313", "314", "315", "316"]
data_connected_roaming_notification_included_mcc_mncs = ["310032", "310033", "310110", "310140", "310370", "310400", "310470", "310500", "310970", "311170", "311250"]
data_limit_threshold_bytes = 107374182400
disconnect_cause_network_busy = [60]
display_hd_plus_icon = true
editable_voicemail_number_setting = false
emergency_call_to_satellite_t911_handover_timeout_millis = 20000
emergency_messaging_supported = true
emergency_number_prefix = ["*272"]
enable_carrier_display_name_resolver = true
enable_nr_advanced_for_roaming = false
gba_ua_tls_cipher_suite = 47
gsm_roaming_networks = ["310032", "310033", "310110", "310140", "310370", "310400", "310470", "310500", "310970", "311170", "311250"]
hide_enhanced_4g_lte = true
hide_tty_hco_vco_with_rtt = true
ignore_rtt_mode_setting = true
ims_reasoninfo_mapping = ["510|Call completed elsewhere|1014", "*|Call is dropped due to Wi-Fi signal is degraded|1407"]
imsi_key_availability = 2
imsi_key_download_url = "https://eas3.msg.t-mobile.com:8188/ses/android/getWifiImsiEncryptionCertificate"
inflate_signal_strength = true
iwlan_handover_policy = ["source=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN|UNKNOWN, target=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN, type=disallowed, capabilities=EIMS|MMS|XCAP|CBS", "source=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN|UNKNOWN, target=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN, roaming=true, type=disallowed, capabilities=IMS", "source=IWLAN|UNKNOWN, target=GERAN|UTRAN, type=disallowed, capabilities=IMS", "source=GERAN|UTRAN, target=IWLAN, type=disallowed, capabilities=IMS", "source=EUTRAN|NGRAN|IWLAN, target=EUTRAN|NGRAN|IWLAN, type=allowed, capabilities=IMS"]
lte_rsrp_thresholds = [-120, -114, -109, -100]
maxImageHeight = 1944
maxImageWidth = 2592
maxMessageSize = 1048576
min_udp_port_4500_nat_timeout_sec = 1680
mmi_two_digit_number_pattern = ["*2"]
mmsCloseConnection = true
mmsRoamingAutoRetrieveByDefault = true
nr_advanced_threshold_bandwidth_khz = 40000
nr_timers_reset_on_voice_qos = true
prefer_2g = true
preferred_ike_protocol = 40
ratchet_nr_advanced_bandwidth_if_rrc_idle = true
read_only_apn_types = []
recipientLimit = 20
rtt_downgrade_supported = true
rtt_supported = true
rtt_supported_while_roaming = true
satellite_attach_supported = true
satellite_entitlement_status_refresh_days = 1
satellite_entitlement_supported = true
satellite_ignore_data_roaming_setting = true
satellite_information_redirect_url = "https://www.t-mobile.com/satellitecoverage"
show_data_connected_roaming_notification = true
show_roaming_indicator = false
smsToMmsTextThreshold = 12
support_video_conference_call = true
volte_replacement_rat = 3
vonr_enabled = true
wfc_carrier_name_override_by_pnn = true
wfc_emergency_address_carrier_app = "com.android.imsserviceentitlement/.WfcActivationActivity"
wfc_operator_error_codes = ["REG09|0"]
wfc_spn_format_idx = 1

[settings.config.bsf]
bsf_server_fqdn = "bsf.msg.pc.t-mobile.com"
bsf_server_port = 443
bsf_transport_type = 3

[settings.config.carrier_supported_satellite_services_per_provider]
310210 = [3]
310830 = [2, 3, 6]
312190 = [3]

[settings.config.ims]
enable_presence_capability_exchange = true
enable_presence_publish = true
geolocation_pidf_in_sip_invite_support = [4, 2]
geolocation_pidf_in_sip_register_support = [4, 2]
gruu_enabled = true
ims_user_agent = "PRD-NG114/1 CPM/OMA2.2 RCS-client/UP_2.3 term-#MANUFACTURE#/#MODEL# client-#MANUFACTURE#/#BUILD# OS-Android/#AV# cc/2.37"
request_uri_type = 1

[settings.config.imsemergency]
emergency_lte_preferred_after_nr_failed = true
emergency_over_ims_roaming_supported_3gpp_network_types = [6, 3]
emergency_over_ims_supported_3gpp_network_types = [6, 3]
emergency_over_ims_supported_rats = [6, 3, 5]
emergency_registration_timer_millis = 10000
emergency_scan_timer_sec = 50
retry_emergency_on_ims_pdn = true

[settings.config.imsserviceentitlement]
entitlement_server_url = "https://ts43.eas3.msg.t-mobile.com/google?"
show_vowifi_webview = true
skip_wfc_activation = true

[settings.config.imsss]
network_initiated_ussd_over_ims_supported = false
ut_as_server_fqdn = "xcap.msg.pc.t-mobile.com"
ut_as_server_port = 443
ut_server_based_services = [20, 12, 18, 14, 19, 21, 15, 16, 17, 13, 1, 3, 4, 7, 6, 5, 2, 0, 8, 9, 11]
ut_terminal_based_services = [10]
ut_transport_type = 3
xcap_over_ut_supported_rats = [6, 3, 5, 1, 2]

[settings.config.imsvoice]
audio_inactivity_call_end_reasons = [0, 1, 2]
audio_rtcp_inactivity_timer_millis = 30000
audio_rtp_inactivity_timer_millis = 30000
conference_factory_uri = "8881112663@msg.pc.t-mobile.com"
dedicated_bearer_wait_timer_millis = 40000
include_caller_id_service_codes_in_sip_invite = true
mo_call_request_timeout_millis = 0
ringback_timer_millis = 128000
rtp_packet_loss_rate_threshold = 30
voice_on_default_bearer_supported = true

[settings.config.imsvoice.evs_payload_description.127]
evs_codec_attribute_bitrate = [0, 4]
evs_codec_attribute_ch_aw_recv = 2

[settings.config.imsvt]
video_as_bandwidth_kbps = 560
video_rs_bandwidth_bps = 5200
video_rtp_dscp = 34

[settings.config.iwlan]
diffie_hellman_groups = [14]
epdg_address_priority = [0, 1]
epdg_plmn_priority = [3, 1]
epdg_static_address = "epdg.epc.mnc260.mcc310.pub.3gppnetwork.org"
ike_session_encryption_aes_cbc_key_size = [128, 256]
key_error_policy_config = '[{"ApnName": "*","ErrorTypes": [{"ErrorType": "IKE_PROTOCOL_ERROR_TYPE","ErrorDetails": ["10500"],"RetryArray": ["3600","7200","10800"],"UnthrottlingEvents": ["APM_ENABLE_EVENT","WIFI_DISABLE_EVENT","WIFI_CALLING_DISABLE_EVENT"]},{"ErrorType": "IKE_PROTOCOL_ERROR_TYPE","ErrorDetails": ["15500"],"NumAttemptsPerFqdn": "6","RetryArray": ["0","0","300","600","1200","0","0","0","300","600","1200","-1"],"UnthrottlingEvents": ["APM_ENABLE_EVENT","WIFI_DISABLE_EVENT","WIFI_CALLING_DISABLE_EVENT"]},{"ErrorType": "IKE_PROTOCOL_ERROR_TYPE","ErrorDetails": ["11001","11011"],"RetryArray": [],"UnthrottlingEvents": []},{"ErrorType": "IKE_PROTOCOL_ERROR_TYPE","ErrorDetails": ["8192"],"RetryArray": ["5","10","10","20","40","80","160","320","640","1280","1800","3600","-1"],"UnthrottlingEvents": ["APM_ENABLE_EVENT","WIFI_DISABLE_EVENT","WIFI_CALLING_DISABLE_EVENT"],"HandoverAttemptCount": "3"}]}]'
supported_integrity_algorithms = [5, 12]
supported_prf_algorithms = [2, 4, 5]
supports_child_session_multiple_sa_proposals = false
supports_ike_session_multiple_sa_proposals = false

[settings.config.qns]
idle_eutran_rsrp = [-109, -114]
idle_geran_rssi = [-95, -105]
idle_ngran_ssrsrp = [-109, -114]
idle_utran_ecno = [-10, -15]
idle_utran_rscp = [-100, -110]
idle_wifi_rssi = [-70, -80]
ims_wlan_hysteresis_timer_ms = [10000, 10000, 10000]
ims_wwan_hysteresis_timer_ms = [10000, 10000, 10000]
mms_rat_preference = 2
video_eutran_rsrp = [-109, -114]
video_ngran_ssrsrp = [-109, -114]
video_wifi_rssi = [-70, -80]
voice_eutran_rsrp = [-109, -114]
voice_ngran_ssrsrp = [-109, -114]
voice_wifi_rssi = [-70, -80]

[settings.config.vendor_ims]
carrier_video_avsync_mic_delay_millis = 55

[settings.config.wifi]
avoid_5ghz_softap_for_laa = true
avoid_5ghz_wifi_direct_for_laa = true
carrier_profiles_version = 4
passpoint_profiles = ['<?xml version="1.0" encoding="UTF-8"?><PasspointProfile><PPSMO><![CDATA[<MgmtTree xmlns="syncml:dmddf1.2"><VerDTD>1.2</VerDTD><Node><NodeName>PerProviderSubscription</NodeName><RTProperties><Type><DDFName>urn:wfa:mo:hotspot2dot0-perprovidersubscription:1.0</DDFName></Type></RTProperties><Node><NodeName>i001</NodeName><Node><NodeName>HomeSP</NodeName><Node><NodeName>FriendlyName</NodeName><Value>T-Mobile Passpoint</Value></Node><Node><NodeName>FQDN</NodeName><Value>t-mobile.com</Value></Node></Node><Node><NodeName>Credential</NodeName><Node><NodeName>Realm</NodeName><Value>wlan.mnc260.mcc310.3gppnetwork.org</Value></Node><Node><NodeName>SIM</NodeName><Node><NodeName>IMSI</NodeName><Value>310260*</Value></Node><Node><NodeName>EAPType</NodeName><Value>23</Value></Node></Node></Node></Node></Node></MgmtTree>]]></PPSMO></PasspointProfile>', '<?xml version="1.0" encoding="UTF-8"?><PasspointProfile><PPSMO><![CDATA[<MgmtTree xmlns="syncml:dmddf1.2"><VerDTD>1.2</VerDTD><Node><NodeName>PerProviderSubscription</NodeName><RTProperties><Type><DDFName>urn:wfa:mo:hotspot2dot0-perprovidersubscription:1.0</DDFName></Type></RTProperties><Node><NodeName>i001</NodeName><Node><NodeName>HomeSP</NodeName><Node><NodeName>FriendlyName</NodeName><Value>T-Mobile Passpoint</Value></Node><Node><NodeName>FQDN</NodeName><Value>t-mobile.com</Value></Node></Node><Node><NodeName>Credential</NodeName><Node><NodeName>Realm</NodeName><Value>wlan.mnc310.mcc310.3gppnetwork.org</Value></Node><Node><NodeName>SIM</NodeName><Node><NodeName>IMSI</NodeName><Value>310310*</Value></Node><Node><NodeName>EAPType</NodeName><Value>23</Value></Node></Node></Node></Node></Node></MgmtTree>]]></PPSMO></PasspointProfile>']

[[settings.vendor_configs.client]]
name = "rcs"
value = "CsMkChtjYXJyaWVyX3Byb3Zpc2lvbmluZ19zdHJpbmcSoyQ8P3htbCB2ZXJzaW9uPSIxLjAiPz48UkNTQ29uZmlnPjx3YXAtcHJvdmlzaW9uaW5nZG9jIHZlcnNpb249IjEuMSI+PGNoYXJhY3RlcmlzdGljIHR5cGU9IlZFUlMiPjxwYXJtIG5hbWU9InZlcnNpb24iIHZhbHVlPSIxNzA5MDYxMDQwIi8+PHBhcm0gbmFtZT0idmFsaWRpdHkiIHZhbHVlPSI4NjQwMCIvPjwvY2hhcmFjdGVyaXN0aWM+PGNoYXJhY3RlcmlzdGljIHR5cGU9IkFQUExJQ0FUSU9OIj48cGFybSBuYW1lPSJBcHBJRCIgdmFsdWU9ImFwMjAwOCIvPjxwYXJtIG5hbWU9Ik5hbWUiIHZhbHVlPSJSQ1MgU2V0dGluZ3MiLz48cGFybSBuYW1lPSJBcHBSZWYiIHZhbHVlPSJyY3MiLz48Y2hhcmFjdGVyaXN0aWMgdHlwZT0iSU1TIj48cGFybSBuYW1lPSJUby1BcHBSZWYiIHZhbHVlPSJpbXMiLz48Y2hhcmFjdGVyaXN0aWMgdHlwZT0iRXh0Ij48cGFybSBuYW1lPSJyY3NWb2x0ZVNpbmdsZVJlZ2lzdHJhdGlvbiIgdmFsdWU9IjEiLz48L2NoYXJhY3RlcmlzdGljPjwvY2hhcmFjdGVyaXN0aWM+PGNoYXJhY3RlcmlzdGljIHR5cGU9IlNFUlZJQ0VTIj48cGFybSBuYW1lPSJzdXBwb3J0ZWRSQ1NQcm9maWxlVmVyc2lvbnMiIHZhbHVlPSJVUDIuMyIvPjxwYXJtIG5hbWU9IkNoYXRBdXRoIiB2YWx1ZT0iMSIvPjxwYXJtIG5hbWU9Ikdyb3VwQ2hhdEF1dGgiIHZhbHVlPSIxIi8+PHBhcm0gbmFtZT0iZnRBdXRoIiB2YWx1ZT0iMSIvPjxwYXJtIG5hbWU9InN0YW5kYWxvbmVNc2dBdXRoIiB2YWx1ZT0iMCIvPjxwYXJtIG5hbWU9Imdlb2xvY1B1c2hBdXRoIiB2YWx1ZT0iMSIvPjxwYXJtIG5hbWU9IklSOTRWaWRlb0FVVEgiIHZhbHVlPSIxIi8+PHBhcm0gbmFtZT0iY29tcG9zZXJBdXRoIiB2YWx1ZT0iMiIvPjxwYXJtIG5hbWU9InNoYXJlZE1hcEF1dGgiIHZhbHVlPSIwIi8+PHBhcm0gbmFtZT0ic2hhcmVkU2tldGNoQXV0aCIgdmFsdWU9IjAiLz48cGFybSBuYW1lPSJwb3N0Q2FsbEF1dGgiIHZhbHVlPSIwIi8+PGNoYXJhY3RlcmlzdGljIHR5cGU9IkV4dCI+PGNoYXJhY3RlcmlzdGljIHR5cGU9IkRhdGFPZmYiPjxwYXJtIG5hbWU9InJjc01lc3NhZ2luZ0RhdGFPZmYiIHZhbHVlPSIwIi8+PHBhcm0gbmFtZT0iZmlsZVRyYW5zZmVyRGF0YU9mZiIgdmFsdWU9IjAiLz48cGFybSBuYW1lPSJzbXNvSVBEYXRhT2ZmIiB2YWx1ZT0iMSIvPjxwYXJtIG5hbWU9Im1tc0RhdGFPZmYiIHZhbHVlPSIwIi8+PHBhcm0gbmFtZT0iY29udGVudFNoYXJlRGF0YU9mZiIgdmFsdWU9IjAiLz48cGFybSBuYW1lPSJ2b2x0ZURhdGFPZmYiIHZhbHVlPSIxIi8+PHBhcm0gbmFtZT0iaXI5NERhdGFPZmYiIHZhbHVlPSIwIi8+PHBhcm0gbmFtZT0icHJlQW5kUG9zdENhbGxEYXRhT2ZmICIgdmFsdWU9IjEiLz48cGFybSBuYW1lPSJzeW5jRGF0YU9mZiAiIHZhbHVlPSIwIi8+PC9jaGFyYWN0ZXJpc3RpYz48L2NoYXJhY3RlcmlzdGljPjwvY2hhcmFjdGVyaXN0aWM+PGNoYXJhY3RlcmlzdGljIHR5cGU9IlBSRVNFTkNFIj48cGFybSBuYW1lPSJQdWJsaXNoVGltZXIiIHZhbHVlPSIzNjAwIi8+PHBhcm0gbmFtZT0iTmlja05hbWVMZW5ndGgiIHZhbHVlPSIyMDAiLz48Y2hhcmFjdGVyaXN0aWMgdHlwZT0iTG9jYXRpb24iPjxwYXJtIG5hbWU9IlRleHRNYXhMZW5ndGgiIHZhbHVlPSIyMDAiLz48cGFybSBuYW1lPSJMb2NJbmZvTWF4VmFsaWRUaW1lIiB2YWx1ZT0iMzYwMCIvPjwvY2hhcmFjdGVyaXN0aWM+PGNoYXJhY3RlcmlzdGljIHR5cGU9IkV4dCIvPjxwYXJtIG5hbWU9ImNsaWVudC1vYmotZGF0YWxpbWl0IiB2YWx1ZT0iNDA5NiIvPjxwYXJtIG5hbWU9ImNvbnRlbnQtc2VydmVydXJpIiB2YWx1ZT0iIi8+PHBhcm0gbmFtZT0ic291cmNlLXRocm90dGxlcHVibGlzaCIgdmFsdWU9IjMwIi8+PHBhcm0gbmFtZT0ibWF4LW51bWJlci1vZnN1YnNjcmlwdGlvbnMtaW5wcmVzZW5jZS1saXN0IiB2YWx1ZT0iMTAiLz48cGFybSBuYW1lPSJzZXJ2aWNlLXVyaXRlbXBsYXRlIiB2YWx1ZT0icmNzIi8+PHBhcm0gbmFtZT0iUkxTLVVSSSIgdmFsdWU9IiIvPjwvY2hhcmFjdGVyaXN0aWM+PGNoYXJhY3RlcmlzdGljIHR5cGU9Ik1FU1NBR0lORyI+PGNoYXJhY3RlcmlzdGljIHR5cGU9IlN0YW5kYWxvbmVNc2ciPjxwYXJtIG5hbWU9Ik1heFNpemUiIHZhbHVlPSIxMDI0MCIvPjxwYXJtIG5hbWU9IlN3aXRjaG92ZXJTaXplIiB2YWx1ZT0iMTMwMCIvPjxwYXJtIG5hbWU9ImV4cGxvZGVyLXVyaSIgdmFsdWU9IlgiLz48L2NoYXJhY3RlcmlzdGljPjxjaGFyYWN0ZXJpc3RpYyB0eXBlPSJDaGF0Ij48cGFybSBuYW1lPSJtYXhfYWRob2NfZ3JvdXBfc2l6ZSIgdmFsdWU9IjEwMCIvPjxwYXJtIG5hbWU9ImNvbmYtZmN0eS11cmkiIHZhbHVlPSJzaXA6YWRob2NAbXNnLnBjLnQtbW9iaWxlLmNvbSIvPjxwYXJtIG5hbWU9IkF1dEFjY2VwdCIgdmFsdWU9IjEiLz48cGFybSBuYW1lPSJBdXRBY2NlcHRHcm91cENoYXQiIHZhbHVlPSIxIi8+PHBhcm0gbmFtZT0iVGltZXJJZGxlIiB2YWx1ZT0iMjEwIi8+PHBhcm0gbmFtZT0iTWF4U2l6ZSIgdmFsdWU9IjgxOTIiLz48cGFybSBuYW1lPSJDaGF0UmV2b2tlVGltZXIiIHZhbHVlPSIwIi8+PHBhcm0gbmFtZT0icmVjb25uZWN0R3VhcmRUaW1lciIgdmFsdWU9IjAiLz48cGFybSBuYW1lPSJjZnNUcmlnZ2VyIiB2YWx1ZT0iIi8+PC9jaGFyYWN0ZXJpc3RpYz48cGFybSBuYW1lPSJtYXgxVG9NYW55UmVjaXBpZW50cyIgdmFsdWU9IjUiLz48cGFybSBuYW1lPSIxdG9NYW55U2VsZWN0ZWRUZWNoIiB2YWx1ZT0iMSIvPjxwYXJtIG5hbWU9ImRpc3BsYXlOb3RpZmljYXRpb25Td2l0Y2giIHZhbHVlPSIwIi8+PGNoYXJhY3RlcmlzdGljIHR5cGU9IkZpbGVUcmFuc2ZlciI+PHBhcm0gbmFtZT0iZnRXYXJuU2l6ZSIgdmFsdWU9IjAiLz48cGFybSBuYW1lPSJNYXhTaXplRmlsZVRyIiB2YWx1ZT0iMTAyNDAwIi8+PHBhcm0gbmFtZT0iZnRBdXRBY2NlcHQiIHZhbHVlPSIxIi8+PHBhcm0gbmFtZT0iZnRIVFRQQ1NVUkkiIHZhbHVlPSJodHRwczovL3VlLmZjcy5tc3RvcmUubXNnLnQtbW9iaWxlLmNvbS9yZXN0Y2xpZW50L1YxL0ZDUy9VcGxvYWQiLz48cGFybSBuYW1lPSJmdEhUVFBETFVSSSIgdmFsdWU9IiIvPjxwYXJtIG5hbWU9ImZ0SFRUUENTVXNlciIgdmFsdWU9IiIvPjxwYXJtIG5hbWU9ImZ0SFRUUENTUHdkIiB2YWx1ZT0iIi8+PHBhcm0gbmFtZT0iZnRIVFRQRmFsbGJhY2siIHZhbHVlPSIwIi8+PHBhcm0gbmFtZT0iZnRNYXgxVG9NYW55UmVjaXBpZW50cyIgdmFsdWU9IjAiLz48L2NoYXJhY3RlcmlzdGljPjxjaGFyYWN0ZXJpc3RpYyB0eXBlPSJDaGF0Ym90Ij48cGFybSBuYW1lPSJDaGF0Ym90RGlyZWN0b3J5IiB2YWx1ZT0iaHR0cHM6Ly9kZi5tc2cudC1tb2JpbGUuY29tL3YxL3NlYXJjaGRpciIvPjxwYXJtIG5hbWU9IkJvdGluZm9GUUROUm9vdCIgdmFsdWU9ImRmLm1zZy50LW1vYmlsZS5jb20vYm90aW5mbyIvPjxwYXJtIG5hbWU9IlNwZWNpZmljQ2hhdGJvdHNMaXN0IiB2YWx1ZT0iIi8+PHBhcm0gbmFtZT0iSWRlbnRpdHlJbkVucmljaGVkU2VhcmNoIiB2YWx1ZT0iMSIvPjxwYXJtIG5hbWU9IlByaXZhY3lEaXNhYmxlIiB2YWx1ZT0iMSIvPjxwYXJtIG5hbWU9IkNoYXRib3RNc2dUZWNoIiB2YWx1ZT0iMCIvPjwvY2hhcmFjdGVyaXN0aWM+PGNoYXJhY3RlcmlzdGljIHR5cGU9Ik1lc3NhZ2VTdG9yZSI+PHBhcm0gbmFtZT0iTXNnU3RvcmVVcmwiIHZhbHVlPSIiLz48cGFybSBuYW1lPSJNc2dTdG9yZU5vdGlmVXJsIiB2YWx1ZT0iIi8+PHBhcm0gbmFtZT0iTXNnU3RvcmVBdXRoIiB2YWx1ZT0iMCIvPjxwYXJtIG5hbWU9Ik1zZ1N0b3JlVXNlck5hbWUiIHZhbHVlPSIiLz48cGFybSBuYW1lPSJNc2dTdG9yZVVzZXJQd2QiIHZhbHVlPSIiLz48cGFybSBuYW1lPSJFdmVudFJwdGluZyIgdmFsdWU9IjAiLz48cGFybSBuYW1lPSJBdXRoQXJjaGl2ZSIgdmFsdWU9IiIvPjxwYXJtIG5hbWU9IlNNU1N0b3JlIiB2YWx1ZT0iMCIvPjxwYXJtIG5hbWU9Ik1NU1N0b3JlIiB2YWx1ZT0iMCIvPjwvY2hhcmFjdGVyaXN0aWM+PGNoYXJhY3RlcmlzdGljIHR5cGU9IlBsdWdpbnMiPjxwYXJtIG5hbWU9ImNhdGFsb2dVUkkiIHZhbHVlPSIiLz48L2NoYXJhY3RlcmlzdGljPjxjaGFyYWN0ZXJpc3RpYyB0eXBlPSJFeHQiLz48L2NoYXJhY3RlcmlzdGljPjxjaGFyYWN0ZXJpc3RpYyB0eXBlPSJDQVBESVNDT1ZFUlkiPjxwYXJtIG5hbWU9ImRpc2FibGVJbml0aWFsQWRkcmVzc0Jvb2tTY2FuIiB2YWx1ZT0iMSIvPjxwYXJtIG5hbWU9ImNhcEluZm9FeHBpcnkiIHZhbHVlPSI4NjQwMCIvPjxwYXJtIG5hbWU9Im5vblJDU2NhcEluZm9FeHBpcnkiIHZhbHVlPSI2MDQ4MDAiLz48cGFybSBuYW1lPSJzZXJ2aWNlQXZhaWxhYmlsaXR5SW5mb0V4cGlyeSIgdmFsdWU9IlgiLz48cGFybSBuYW1lPSJkZWZhdWx0RGlzYyIgdmFsdWU9IjEiLz48Y2hhcmFjdGVyaXN0aWMgdHlwZT0iQ2FwRGlzY292ZXJ5V2hpdGVsaXN0Ij48Y2hhcmFjdGVyaXN0aWMgdHlwZT0iQ2FwRGlzY292ZXJ5QWxsb3dlZFByZWZpeGVzIj48cGFybSBuYW1lPSJQcmVmaXgxIiB2YWx1ZT0iIi8+PHBhcm0gbmFtZT0iUHJlZml4MiIgdmFsdWU9IiIvPjwvY2hhcmFjdGVyaXN0aWM+PC9jaGFyYWN0ZXJpc3RpYz48L2NoYXJhY3RlcmlzdGljPjwvY2hhcmFjdGVyaXN0aWM+PC93YXAtcHJvdmlzaW9uaW5nZG9jPjwvUkNTQ29uZmlnPg=="

[settings.field8]
seconds = 1777512376
