[[carrier_id]]
mcc_mnc = "52000"

[carrier_id.mvno_data]
kind = "gid1"
value = "01"

[[carrier_id]]
mcc_mnc = "52004"

[settings]
version = 77000000003

[[settings.apns.apn]]
name = "TRUE-H INTERNET"
value = "internet"
type = ["default", "supl"]
user = "true"
password = "true"
authtype = 1

[[settings.apns.apn]]
name = "TRUE-H MMS"
value = "hmms"
type = ["mms"]
user = "true"
password = "true"
authtype = 1
mmsc = "http://mms.trueh.com:8002/"
mmsc_proxy = "10.4.7.39"
mmsc_proxy_port = "8080"

[[settings.apns.apn]]
name = "IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|18|20"
protocol = "ipv6"
roaming_protocol = "ipv4v6"
user_visible = false

[settings.config]
carrier_default_wfc_ims_mode = 1
carrier_volte_available = true
iwlan_handover_policy = ["source=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN|UNKNOWN, target=GERAN|UTRAN|EUTRAN|NGRAN|IWLAN, type=disallowed, capabilities=EIMS|MMS|XCAP|CBS", "source=IWLAN|UNKNOWN, target=GERAN|UTRAN|NGRAN, type=disallowed, capabilities=IMS", "source=GERAN|UTRAN|NGRAN, target=IWLAN, type=disallowed, capabilities=IMS", "source=EUTRAN|IWLAN, target=EUTRAN|IWLAN, type=allowed, capabilities=IMS"]
roaming_operator = ["520"]
show_4g_for_lte_data_icon = true
wfc_spn_format_idx = 1

[settings.config.imsemergency]
emergency_domain_preference = [2, 1]
emergency_domain_preference_roaming = [2, 1]
emergency_over_ims_supported_rats = [3]

[settings.config.imsss]
xcap_over_ut_supported_rats = []

[settings.config.imsvoice]
conference_factory_uri = "conf-factory.ics.mnc004.mcc520.3gppnetwork.org"

[settings.config.imsvoice.audio_codec_capability_payload_types]
amrnb_payload_type = [98, 103]
amrwb_payload_type = [100, 105]
dtmfnb_payload_type = [97]
dtmfwb_payload_type = [96]

[settings.config.iwlan]
epdg_address_priority = [0]
epdg_static_address = "epdg.epc.mnc004.mcc520.pub.3gppnetwork.org"

[settings.field8]
seconds = 1773841160
