[[carrier_id]]
mcc_mnc = "46689"

[settings]
version = 77000000005

[[settings.apns.apn]]
name = "台灣大哥大TS (Internet)"
value = "internet"
type = ["default", "supl"]

[[settings.apns.apn]]
name = "台灣大哥大TS (MMS)"
value = "internet"
type = ["mms"]
mmsc = "http://mms.vibo.net.tw"
mmsc_proxy = "172.24.128.36"
mmsc_proxy_port = "8080"
user_editable = false

[[settings.apns.apn]]
name = "台灣大哥大TS (IMS)"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|18|20"
user_editable = false

[settings.config]
_5g_icon_configuration = "connected_mmwave:5G,connected:5G,not_restricted_rrc_idle:5G"
_5g_icon_display_grace_period = "connected_mmwave,legacy,31;connected,legacy,31;connected_mmwave,not_restricted_rrc_con,31;connected,not_restricted_rrc_con,31;not_restricted_rrc_idle,not_restricted_rrc_con,15"
allow_hold_call_during_emergency = false
carrier_default_2g_protection_enabled = true
carrier_supports_ss_over_ut = true
carrier_ussd_method = 2
carrier_volte_available = true
hide_enhanced_4g_lte = true
hide_lte_plus_data_icon = false
lte_endc_using_user_data_for_rrc_detection = true
support_ims_conference_call = false
support_ims_conference_event_package = false

[settings.config.ims]
sip_timer_j_millis = 32000
sip_timer_t4_millis = 20000

[settings.config.imsemergency]
emergency_domain_preference = [2, 1]
emergency_domain_preference_roaming = [2, 1]
emergency_over_ims_supported_rats = [3]
emergency_qos_precondition_supported = false
prefer_ims_emergency_when_voice_calls_on_cs = true

[settings.config.imssms]
sms_over_ims_supported_rats = []

[settings.config.imsss]
network_initiated_ussd_over_ims_supported = false
ut_server_based_services = []
ut_terminal_based_services = [0]
xcap_over_ut_supported_rats = []

[settings.config.imsvoice]
minimum_session_expires_timer_sec = 1800
ringback_timer_millis = 35000
ringing_timer_millis = 45000
srvcc_type = []

[settings.config.imsvoice.amrnb_payload_description.108]
amr_codec_attribute_payload_format = 1

[settings.config.imsvoice.amrwb_payload_description.110]
amr_codec_attribute_payload_format = 1

[settings.config.imsvoice.audio_codec_capability_payload_types]
amrnb_payload_type = [102, 108]
amrwb_payload_type = [104, 110]
dtmfnb_payload_type = [97]
dtmfwb_payload_type = [96]

[settings.config.imsvt]
video_qos_precondition_supported = false

[settings.config.rilext]
ims_prefer_apm_normal_ecc_enable = true

[settings.field8]
seconds = 1769617073
