[[carrier_id]]
mcc_mnc = "405823"

[[carrier_id]]
mcc_mnc = "405825"

[[carrier_id]]
mcc_mnc = "405826"

[[carrier_id]]
mcc_mnc = "405828"

[[carrier_id]]
mcc_mnc = "405829"

[[carrier_id]]
mcc_mnc = "405830"

[[carrier_id]]
mcc_mnc = "405831"

[[carrier_id]]
mcc_mnc = "405832"

[[carrier_id]]
mcc_mnc = "405833"

[[carrier_id]]
mcc_mnc = "405835"

[[carrier_id]]
mcc_mnc = "405836"

[[carrier_id]]
mcc_mnc = "405837"

[[carrier_id]]
mcc_mnc = "405838"

[[carrier_id]]
mcc_mnc = "405839"

[[carrier_id]]
mcc_mnc = "405841"

[[carrier_id]]
mcc_mnc = "405842"

[[carrier_id]]
mcc_mnc = "405843"

[[carrier_id]]
mcc_mnc = "405932"

[[settings.apns.apn]]
name = "Videocon MMS"
value = "vgprs.com"
type = ["mms"]
mmsc = "http://10.202.4.119:10021/mmsc/"
mmsc_proxy = "10.202.5.145"
mmsc_proxy_port = "8799"
protocol = "ipv4v6"

[[settings.apns.apn]]
name = "Videocon"
value = "vinternet.com"
type = ["default", "supl"]
protocol = "ipv4v6"

[settings.config]
