[[carrier_id]]
mcc_mnc = "20205"

[settings]
version = 77000000009

[[settings.apns.apn]]
name = "Vodafone GR"
value = ""
type = ["ia"]
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[[settings.apns.apn]]
name = "Vf Internet"
value = "internet.vodafone.gr"
type = ["default", "supl"]
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "Vf MMS"
value = "mms.vodafone.net"
type = ["mms"]
user = "user"
password = "pass"
authtype = 1
mmsc = "http://mms.vodafone.gr"
mmsc_proxy = "213.249.19.49"
mmsc_proxy_port = "5080"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[[settings.apns.apn]]
name = "IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|18|20"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[[settings.apns.apn]]
name = "hos"
value = "hos"
type = ["xcap"]
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"

[settings.config]
carrier_certificate = ["DCFD5757F7AE448C5F79D224D33906880D89D3ABBF887EAC17226DBB52DFD6F6:com.myvodafone.android"]
carrier_supports_ss_over_ut = true
carrier_volte_available = true
carrier_wfc_ims_available = true
default_vm_number = "121"
display_hd_plus_icon = true
ignore_rtt_mode_setting = true
prefer_2g = true
rtt_downgrade_supported = true
rtt_supported = true
rtt_supported_while_roaming = true
wfc_spn_format_idx = 1

[settings.config.bsf]
bsf_server_fqdn = "bsf.ims.mnc005.mcc202.pub.3gppnetwork.org"

[settings.config.imsemergency]
emergency_domain_preference_roaming = [2, 1]

[settings.config.imsss]
ut_as_server_fqdn = "xcap.ims.mnc005.mcc202.pub.3gppnetwork.org"
ut_server_based_services = [20, 12, 18, 14, 19, 21, 15, 16, 17, 13, 1, 3, 4, 7, 6, 5, 2, 0, 8, 9, 11]
ut_terminal_based_services = [10]
xcap_over_ut_supported_rats = [5, 6, 3, 1, 2]

[settings.config.imsvoice.evs_payload_description.127]
codec_attribute_cmr = 3
evs_codec_attribute_bitrate = [0, 6]

[settings.config.imswfc]
emergency_call_over_emergency_pdn = true

[settings.config.iwlan]
diffie_hellman_groups = [2, 14]
epdg_address_priority = [0]
epdg_static_address = "epdg.epc.mnc005.mcc202.pub.3gppnetwork.org"
key_error_policy_config = '[{"ApnName": "*","ErrorTypes": [{"ErrorType": "IKE_PROTOCOL_ERROR_TYPE","ErrorDetails": ["9002"],"RetryArray": ["1800", "-1"],"UnthrottlingEvents": ["APM_ENABLE_EVENT", "WIFI_DISABLE_EVENT", "WIFI_AP_CHANGED_EVENT", "WIFI_CALLING_DISABLE_EVENT"]}]}]'

[settings.config.qns]
sos_transport_type = 2

[settings.field8]
seconds = 1770819167
