[[carrier_id]]
mcc_mnc = "53001"

[settings]
version = 77000000002

[[settings.apns.apn]]
name = "VFNZ Gateway"
value = "live.vodafone.com"
type = ["mms"]
mmsc = "http://pxt.vodafone.net.nz/pxtsend"
mmsc_proxy = "172.30.38.3"
mmsc_proxy_port = "8080"

[[settings.apns.apn]]
name = "VFNZ Internet"
value = "vodafone"
type = ["default", "supl"]

[[settings.apns.apn]]
name = "IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|18|20"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[[settings.apns.apn]]
name = "XCAP"
value = "xcap"
type = ["xcap"]
user_visible = false

[settings.config]
carrier_supports_ss_over_ut = true
carrier_volte_available = true
carrier_wfc_ims_available = true
show_4g_for_lte_data_icon = true
wfc_spn_format_idx = 1

[settings.config.bsf]
bsf_server_port = 443
bsf_transport_type = 3

[settings.config.imsemergency]
emergency_domain_preference = [2, 1]
emergency_domain_preference_roaming = [2, 1]
emergency_over_ims_supported_rats = [3]

[settings.config.imsss]
ut_as_server_port = 443
ut_transport_type = 3
xcap_over_ut_supported_rats = [5, 6, 3, 1, 2]

[settings.config.imsvoice.audio_codec_capability_payload_types]
amrnb_payload_type = [98, 103]
amrwb_payload_type = [100, 105]
dtmfnb_payload_type = [97]
dtmfwb_payload_type = [96]

[settings.config.iwlan]
key_error_policy_config = '[{"ApnName": "*","ErrorTypes": [{"ErrorType": "IKE_PROTOCOL_ERROR_TYPE","ErrorDetails": ["9002"],"RetryArray": ["1800", "-1"],"UnthrottlingEvents": ["APM_ENABLE_EVENT", "WIFI_DISABLE_EVENT", "WIFI_AP_CHANGED_EVENT", "WIFI_CALLING_DISABLE_EVENT"]}]}]'

[settings.field8]
seconds = 1747202480
