[[carrier_id]]
mcc_mnc = "334140"

[carrier_id.mvno_data]
kind = "spn"
value = "WiMO"

[[settings.apns.apn]]
name = "Wimo"
value = "internet.wimo.com"
type = ["default"]

[[settings.apns.apn]]
name = "Wimo"
value = "ims"
type = ["ims"]

[settings.config]
