[[carrier_id]]
mcc_mnc = "21404"

[carrier_id.mvno_data]
kind = "spn"
value = "Virgin telco"

[[carrier_id]]
mcc_mnc = "21404"

[carrier_id.mvno_data]
kind = "spn"
value = "Tu Operador"

[[carrier_id]]
mcc_mnc = "21404"

[carrier_id.mvno_data]
kind = "spn"
value = "Cablemovil"

[[carrier_id]]
mcc_mnc = "21404"

[carrier_id.mvno_data]
kind = "spn"
value = "Lycamobile"

[[carrier_id]]
mcc_mnc = "21404"

[carrier_id.mvno_data]
kind = "spn"
value = "EUSKALTEL"

[[carrier_id]]
mcc_mnc = "21404"

[carrier_id.mvno_data]
kind = "spn"
value = "Pepephone"

[[carrier_id]]
mcc_mnc = "21404"

[carrier_id.mvno_data]
kind = "spn"
value = "telecable"

[[carrier_id]]
mcc_mnc = "21404"

[carrier_id.mvno_data]
kind = "spn"
value = "Populoos"

[[carrier_id]]
mcc_mnc = "21404"

[carrier_id.mvno_data]
kind = "spn"
value = "RACCtel+"

[[carrier_id]]
mcc_mnc = "21404"

[carrier_id.mvno_data]
kind = "spn"
value = "LLAMAYA"

[[carrier_id]]
mcc_mnc = "21404"

[carrier_id.mvno_data]
kind = "spn"
value = "LEBARA"

[[carrier_id]]
mcc_mnc = "21404"

[carrier_id.mvno_data]
kind = "spn"
value = "SIMple"

[[carrier_id]]
mcc_mnc = "21404"

[carrier_id.mvno_data]
kind = "spn"
value = "mobilR"

[[carrier_id]]
mcc_mnc = "21404"

[carrier_id.mvno_data]
kind = "spn"
value = "Sweno"

[[carrier_id]]
mcc_mnc = "21404"

[carrier_id.mvno_data]
kind = "spn"
value = "Yoigo"

[[carrier_id]]
mcc_mnc = "21404"

[carrier_id.mvno_data]
kind = "spn"
value = "GUUK"

[[carrier_id]]
mcc_mnc = "21404"

[carrier_id.mvno_data]
kind = "spn"
value = "RACC"

[[carrier_id]]
mcc_mnc = "21404"

[carrier_id.mvno_data]
kind = "spn"
value = "R"

[settings]
version = 77000000004

[[settings.apns.apn]]
name = "Internet"
value = "internet"
type = ["default", "supl"]

[[settings.apns.apn]]
name = "IMS"
value = "ims"
type = ["ims"]
bearer_bitmask = "14|18|20"
protocol = "ipv4v6"
roaming_protocol = "ipv4v6"
user_visible = false

[[settings.apns.apn]]
name = "hos"
value = "hos"
type = ["xcap"]
user_visible = false

[settings.config]
carrier_certificate = ["4eed01853eb98d0e48a6d6e88862f60bcf1f228a30425197ad5db0844b596003:com.yoigo.miyoigo,com.yoigo.miyoigo.staging", "3835ed964ace7b9eae2c811f76a4c03bd93262f1b344f0c899d5214e7151071a:com.masmovil.masmovil,com.masmovil.masmovil.staging", "7ba63f627d11774be2630257cd05ad49fa11e4e7ca541b714e38e41971b90aa1:com.llamaya.millamaya,com.llamaya.millamaya.staging", "28a0475406d499e5e553167b0959632d9611117c9a70e1047229a51de2a6acda:eus.guuk.miguuk,eus.guuk.miguuk.staging", "2b42d2766b78a10d6c46e2c5db82da2bed7a0422a922c6e16004d48d1ff17a47:es.sweno.misweno,es.sweno.misweno.staging", "4f5801dec3ef6091a68cb3189b4c87d33dfa51f358843a9664b3efe331c0b915:com.lycamobile.milycamobile,com.lycamobile.milycamobile.staging", "c83e521c6ea926a445fc14c63d7d28af88475f5cd673b213c046970820b0917f:com.lebara.milebara,com.lebara.milebara.staging", "6bda757bf173446a88ff7207e573417b3013e305d1d762feb308c72c1824c6c5:ekt.moveus.applikate,ekt.moveus.applikate.staging", "612ad665126e2392c90f2a9893d7b6d0588aa28cd66510dca76231e239cc8202:com.mundor.apps.cliente.autenticacion,com.mundor.apps.cliente.autenticacion.staging", "89f4dcb6171434668ff3f9318fe350e658ad9cf524a1829ac875199dabfb009c:es.telecable.app.corporativa,es.telecable.app.corporativa.staging", "d323a4b7806b1ba157732d4bc43970ba4c9f6163fa065b7512504fbe4ab37f77:es.virgintelco.myapp,es.virgintelco.myapp.staging", "1faa0158c092e9fa95a68eaffc518b83acd5af316c244661404aefebf590d435:com.racctelplus.app,com.racctelplus.app.staging", "dfbd378c05733f6e85ed6f048c97c587282eb41bc8e0eb0a4734b7bb85827597:com.yoigo.miyoigo.debug,com.yoigo.miyoigo.staging.debug,com.masmovil.masmovil.debug,com.masmovil.masmovil.staging.debug,com.llamaya.millamaya.debug,com.llamaya.millamaya.staging.debug,eus.guuk.miguuk.debug,eus.guuk.miguuk.staging.debug,es.sweno.misweno.debug,es.sweno.misweno.staging.debug,com.lycamobile.milycamobile.debug,com.lycamobile.milycamobile.staging.debug,com.lebara.milebara.debug,com.lebara.milebara.staging.debug,ek.moveus.applikate.debug,ek.moveus.applikate.staging.debug,com.mundor.apps.cliente.autenticacion.debug,com.mundor.apps.cliente.autenticacion.staging.debug,es.telecable.app.corporativa.debug,es.telecable.app.corporativa.staging.debug,es.virgintelco.myapp.debug,es.virgintelco.myapp.staging.debug,com.racctelplus.app.debug,com.racctelplus.app.staging.debug"]
carrier_supports_ss_over_ut = true
carrier_volte_available = true
carrier_wfc_ims_available = true
default_vm_number = "633"
enabledMMS = false
ignore_rtt_mode_setting = true
non_roaming_operator = ["21401", "21402", "21403", "21405", "21406", "21407", "21408", "21409", "214010", "214011", "214012", "214013", "214014", "214015", "214016", "214017", "214018", "214019", "214020", "214021"]
rtt_downgrade_supported = true
rtt_supported = true
rtt_supported_while_roaming = true
show_4g_for_lte_data_icon = true
unloggable_numbers = ["900018018", "016", "021", "024", "028", "116000", "116111", "900202010"]
wfc_spn_format_idx = 1

[settings.config.imsemergency]
emergency_domain_preference = [2, 1]
emergency_domain_preference_roaming = [2, 1]
emergency_over_ims_supported_rats = [3]

[settings.config.imsss]
xcap_over_ut_supported_rats = [6, 3, 5, 1, 2]

[settings.config.imsvoice.audio_codec_capability_payload_types]
amrnb_payload_type = [98, 103]
amrwb_payload_type = [100, 105]
dtmfnb_payload_type = [97]
dtmfwb_payload_type = [96]

[settings.config.iwlan]
child_sa_rekey_hard_timer_sec = 14400
child_sa_rekey_soft_timer_sec = 14300
diffie_hellman_groups = [14]
dpd_timer_sec = 60
ike_rekey_hard_timer_in_sec = 43200
ike_rekey_soft_timer_sec = 43100

[settings.field8]
seconds = 1772035424
